/* Nava Android 12.1.68 TEST-FIRST — explicit-label aware reader language selector. */
;(function(d,w){
'use strict';
if(w.__navaLanguageV12168)return;w.__navaLanguageV12168=true;
if(!w.__NAVA_ANDROID_APP__||!w.NavaLanguageCoreV12168)return;
var C=w.NavaLanguageCoreV12168,LANGS=C.LANGS,PREFIX='nava_series_language_v12149:',state={index:{byUrl:{},groups:{}},loaded:false,loading:null},observer=null,queued=false;
function clean(v,n){return C.clean(v,n)}function canon(v){return C.canon(v,location.href)}
function pageTitle(){var x=d.querySelector('.nava-reader-title-v2,header h1[itemprop="name"],main h1,h1');return clean(x?x.textContent:d.title,300)}
function seriesName(){var meta=d.querySelector('[data-nava-chapter-meta]'),v=clean(meta&&meta.getAttribute('data-volume-title'),500);if(v){var m=v.match(/^(.*?)(?:\s*[-–—|:]\s*)?(?:cilt|volume|vol\.?)\s*\d+/i);if(m&&clean(m[1]))return clean(m[1],300)}return pageTitle()}
function storageKey(name){return PREFIX+clean(name||seriesName(),300).toLocaleLowerCase('tr-TR').replace(/\s+/g,' ')}
function getSelected(name,available){var saved='';try{saved=localStorage.getItem(storageKey(name))||''}catch(_){}if(available&&available.indexOf(saved)>=0)return saved;if(available&&available.indexOf('TR')>=0)return'TR';return available&&available[0]||'TR'}
function setSelected(name,lang){lang=clean(lang,10).toUpperCase();if(LANGS.indexOf(lang)<0)return;try{localStorage.setItem(storageKey(name),lang)}catch(_){}schedule()}
async function allPosts(){var out=[],start=1,size=500;for(var pass=0;pass<6;pass++){var r=await fetch('/feeds/posts/summary?alt=json&max-results='+size+'&start-index='+start+'&orderby=published&_nava68lang='+Date.now(),{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw new Error('feed '+r.status);var j=await r.json(),a=j&&j.feed&&j.feed.entry||[];out=out.concat(a);if(a.length<size)break;start+=size}return out}
function ready(){if(state.loaded)return Promise.resolve(state.index);if(state.loading)return state.loading;state.loading=(async function(){try{state.index=C.buildIndex(await allPosts())}catch(e){console.warn('Dil verisi alınamadı',e);state.index={byUrl:{},groups:{}}}state.loaded=true;state.loading=null;schedule();return state.index})();return state.loading}
function pageLabels(){var out=[];[].slice.call(d.querySelectorAll('a[rel="tag"],.post-labels a,.labels a,[data-label]')).forEach(function(x){var t=clean(x.getAttribute&&x.getAttribute('data-label')||x.textContent,100);if(t)out.push(t)});return out}
function currentVariants(){var v=C.variantsForUrl(state.index,location.href),explicit=C.explicitLang(pageLabels());if(!explicit)return v;var languages=(v.languages||[]).slice(),targets=Object.assign({},v.targets||{});if(languages.indexOf(explicit)<0)languages.push(explicit);languages=LANGS.filter(function(l){return languages.indexOf(l)>=0});targets[explicit]=canon(location.href);return{current:v.current,languages:languages,targets:targets,show:true,explicitPage:explicit}}
function ensureStyle(){if(d.getElementById('nava-reader-language-style-v12168'))return;var s=d.createElement('style');s.id='nava-reader-language-style-v12168';s.textContent='.nava-reader-language-setting-v12168{box-sizing:border-box;display:grid;grid-template-columns:minmax(84px,.72fr) minmax(0,1.28fr);align-items:center;gap:10px;margin:8px 12px 12px;padding:12px 0 2px;border-top:1px solid rgba(127,145,166,.22);min-width:0;overflow:hidden}.nava-reader-language-copy-v12168{min-width:0;display:grid;gap:2px}.nava-reader-language-copy-v12168 strong{font-size:12px;font-weight:850}.nava-reader-language-copy-v12168 small{font-size:9.5px;opacity:.62}.nava-reader-language-options-v12168{min-width:0;width:100%;max-width:100%;display:flex;flex-wrap:nowrap;justify-content:flex-start;gap:6px;overflow-x:auto!important;overflow-y:hidden!important;-webkit-overflow-scrolling:touch;overscroll-behavior-x:contain;touch-action:pan-x!important;scrollbar-width:none;padding:3px 0 4px;pointer-events:auto}.nava-reader-language-options-v12168::-webkit-scrollbar{display:none}.nava-reader-language-options-v12168 button{flex:0 0 auto;min-width:46px;min-height:34px;padding:0 11px;border:1px solid #d2dce8;border-radius:8px;background:#f8fafc;color:#5e7087;font:800 10px/1 system-ui,-apple-system,"Segoe UI",sans-serif;touch-action:manipulation}.nava-reader-language-options-v12168 button.is-active{border-color:#7898ba;background:#eaf2fb;color:#466184}html.dark.nava-app-v9 .nava-reader-language-setting-v12168{border-color:#334155}html.dark.nava-app-v9 .nava-reader-language-options-v12168 button{background:#182334;border-color:#35475d;color:#cbd5e1}html.dark.nava-app-v9 .nava-reader-language-options-v12168 button.is-active{background:#213047;border-color:#58789d;color:#c6dafc}@media(max-width:360px){.nava-reader-language-setting-v12168{grid-template-columns:76px minmax(0,1fr);gap:7px}.nava-reader-language-options-v12168 button{min-width:44px}}';(d.head||d.documentElement).append(s)}
function readerSetting(){['nava-reader-language-v12167','nava-reader-language-v12166','nava-reader-language-v12165','nava-reader-language-v12149'].forEach(function(id){var x=d.getElementById(id);if(x)x.remove()});var row=d.getElementById('nava-reader-language-v12168'),body=d.body,panel=d.getElementById('nava-reader-settings-v2');if(!(body&&body.classList.contains('nava-app-reader'))||!panel){if(row)row.remove();return}var variants=currentVariants();if(!state.loaded||!variants.show){if(row)row.remove();return}var name=seriesName(),avail=variants.languages,selected=getSelected(name,avail);if(!row){row=d.createElement('section');row.id='nava-reader-language-v12168';row.className='nava-reader-language-setting-v12168';row.innerHTML='<div class="nava-reader-language-copy-v12168"><strong>Dil</strong><small>Bu bölüm için</small></div><div class="nava-reader-language-options-v12168"></div>';panel.append(row)}else if(row.parentNode!==panel)panel.append(row);var sig=selected+'|'+avail.join(',');if(row.dataset.sig===sig)return;row.dataset.sig=sig;var list=row.querySelector('.nava-reader-language-options-v12168');list.replaceChildren();avail.forEach(function(l){var b=d.createElement('button');b.type='button';b.textContent=l;b.dataset.lang=l;b.classList.toggle('is-active',l===selected);b.setAttribute('aria-pressed',l===selected?'true':'false');b.onclick=function(e){e.preventDefault();e.stopPropagation();setSelected(name,l);var target=variants.targets[l];if(target&&canon(target)!==canon(location.href))location.assign(target)};list.append(b)})}
function rowFor(a){return a.closest('li,article,[data-nava-chapter],.nava-chapter-item,.chapter-item,.eplister li,.eplister ul>li,#nava-reader-chapters-v9 li')||a.parentElement||a}
function listAnchors(){var seen={},out=[];[].slice.call(d.querySelectorAll('#clwd a[href],#chapters a[href],[data-nava-chapter-list] a[href],.eplister a[href],#nava-reader-chapters-v9 a[href]')).forEach(function(a){var u=canon(a.href),rec=state.index.byUrl[u];if(!u||!rec||seen[u])return;seen[u]=1;out.push({a:a,row:rowFor(a),rec:rec})});return out}
function applyList(){if(!(d.body&&(d.body.classList.contains('nava-app-series')||d.body.classList.contains('nava-app-volume')))||!state.loaded)return;var items=listAnchors(),groups=new Map(),selected=getSelected(seriesName(),LANGS);items.forEach(function(x){var k=(x.rec.volumeKey||'novol')+'|'+x.rec.chapterNo;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(x)});groups.forEach(function(g){var exact=g.find(function(x){return x.rec.lang===selected}),tr=g.find(function(x){return x.rec.lang==='TR'}),chosen=exact||tr||g[0];g.forEach(function(x){if(x.row)x.row.hidden=x!==chosen})})}
function filterDownloadItems(items,name){items=Array.isArray(items)?items.slice():[];var chapters=items.filter(function(x){return x&&x.kind==='chapter'}),other=items.filter(function(x){return !x||x.kind!=='chapter'});if(!chapters.length)return items;var groups=new Map(),selected=getSelected(name,LANGS);chapters.forEach(function(x){var rec=state.index.byUrl[canon(x.url)],k=rec?((rec.volumeKey||'novol')+'|'+rec.chapterNo):('url|'+canon(x.url));if(!groups.has(k))groups.set(k,[]);groups.get(k).push({item:x,rec:rec})});groups.forEach(function(g){var exact=g.find(function(x){return x.rec&&x.rec.lang===selected}),tr=g.find(function(x){return x.rec&&x.rec.lang==='TR'}),chosen=exact||tr||g[0];other.push(chosen.item)});return other}
w.NavaSeriesLanguageV12149={ready:ready,getLanguage:function(url){var r=state.index.byUrl[canon(url)];return r?r.lang:''},getSelected:function(name,available){return getSelected(name,available)},setSelected:setSelected,filterDownloadItems:async function(items,name){await ready();return filterDownloadItems(items,name)}};
function apply(){applyList();readerSetting()}function schedule(){if(queued)return;queued=true;requestAnimationFrame(function(){queued=false;apply()})}
function init(){ensureStyle();ready();apply();if(d.body&&!observer){observer=new MutationObserver(schedule);observer.observe(d.body,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden','class']})}w.addEventListener('pageshow',function(){setTimeout(schedule,0);setTimeout(schedule,500)},{passive:true})}
if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(document,window);
