/* Nava Android 12.1.63 — single downloaded-library renderer + metadata repair. */
;(function(d,w){
'use strict';
if(w.__navaDownloadedLibraryV12163)return;w.__navaDownloadedLibraryV12163=true;
if(!w.__NAVA_ANDROID_APP__||!w.NavaOffline)return;
var state={seriesOpen:Object.create(null),volumeOpen:Object.create(null)};
function clean(v,n){return String(v==null?'':v).replace(/\s+/g,' ').trim().slice(0,n||600)}
function norm(v){return clean(v,700).toLocaleLowerCase('tr-TR').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function el(t,c,x){var e=d.createElement(t);if(c)e.className=c;if(x!=null)e.textContent=x;return e}
function call(m){try{var f=w.NavaOffline&&w.NavaOffline[m];if(typeof f!=='function')return null;return f.apply(w.NavaOffline,[].slice.call(arguments,1))}catch(_){return null}}
function fmt(n){n=Number(n)||0;if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';if(n<1073741824)return(n/1048576).toFixed(1)+' MB';return(n/1073741824).toFixed(2)+' GB'}
function canon(v){try{var u=new URL(String(v||''),location.href);if(!/(^|\.)verudanava\.(?:com|blogspot\.com)$/i.test(u.hostname))return'';u.hash='';u.search='';u.protocol='https:';u.hostname='www.verudanava.com';u.port='';return u.href.replace(/\/$/,'')}catch(_){return''}}
function slug(v){try{return clean(decodeURIComponent(new URL(String(v||''),location.href).pathname.split('/').filter(Boolean).pop()||'').replace(/\.html?$/i,'').replace(/[-_]+/g,' '),500)}catch(_){return''}}
function no(text,type){var rx=type==='v'?/(?:cilt|volume|vol\.?)\s*([0-9]+(?:\.[0-9]+)?)/i:/(?:bölüm|bolum|chapter|ch\.?|episode|ep\.?)\s*([0-9]+(?:\.[0-9]+)?)/i,m=clean(text,1200).match(rx);return m?m[1]:''}
function stripVolume(v){return clean(v,700).replace(/\s*(?:[-–—|:]\s*)?(?:cilt|volume|vol\.?)\s*\d+(?:\.\d+)?(?:\s*[-–—|:].*)?$/i,'').trim()}
function junk(v){return /^(|nava|icerik|diger|cilt|volume|vol|bolum|chapter|ch|episode|ep)(?:\s*\d+(?:\.\d+)?)?$/.test(norm(v))}
function pretty(v){return clean(v,500).split(' ').map(function(x){return x?x.charAt(0).toLocaleUpperCase('tr-TR')+x.slice(1):''}).join(' ')}
function meta(i){i=i||{};var st=clean(i.seriesTitle,600),vt=clean(i.volumeTitle,200),tt=clean(i.title,600),sl=slug(i.url),mix=[vt,st,tt,sl].join(' '),vn=no(mix,'v'),cn=no(mix,'c'),kind=String(i.kind||'').toLowerCase(),series=stripVolume(st);if(junk(series))series='';if(!series){var ss=stripVolume(sl);if(ss!==sl&&!junk(ss))series=pretty(ss)}var looksVolume=!!vn&&!cn&&(kind==='volume'||!!no(tt,'v')||!!no(sl,'v'));if(looksVolume)kind='volume';else if(cn||kind==='chapter')kind='chapter';return{item:i,url:canon(i.url),series:series,volumeNo:vn,chapterNo:cn,kind:kind,volumeTitle:vt|| (vn?'Cilt '+vn:'')}}
function raw(){try{var x=JSON.parse(call('listDownloads')||'{}');if(!Array.isArray(x.items))x.items=[];return x}catch(_){return{items:[],storageBytes:0}}}
function dedupe(items){var map=Object.create(null),out=[];(items||[]).forEach(function(i){var u=canon(i&&i.url);if(!u)return;if(!map[u]){map[u]=i;out.push(u);return}var a=meta(map[u]),b=meta(i);if((!a.series&&b.series)||(!a.volumeNo&&b.volumeNo)||(!a.chapterNo&&b.chapterNo))map[u]=i});return out.map(function(u){return map[u]})}
function normalize(items){var rows=dedupe(items).map(meta),chapterOwners=Object.create(null),allOwners=Object.create(null);rows.forEach(function(r){if(!r.series)return;allOwners[norm(r.series)]=r.series;if(r.kind==='chapter'&&r.volumeNo){var k=String(r.volumeNo),m=chapterOwners[k]||(chapterOwners[k]=Object.create(null));m[norm(r.series)]=r.series}});var allKeys=Object.keys(allOwners);rows.forEach(function(r){if(r.kind==='volume'&&r.volumeNo){var m=chapterOwners[String(r.volumeNo)]||{},ks=Object.keys(m);if(ks.length===1)r.series=m[ks[0]]}if(!r.series&&r.volumeNo){var m2=chapterOwners[String(r.volumeNo)]||{},ks2=Object.keys(m2);if(ks2.length===1)r.series=m2[ks2[0]]}if(!r.series&&allKeys.length===1)r.series=allOwners[allKeys[0]];if(!r.series)r.series='Diğer'});return rows}
function groups(items){var sm=new Map();normalize(items).forEach(function(r){var sk=norm(r.series),s=sm.get(sk);if(!s){s={name:r.series,items:[],bytes:0,volumes:new Map()};sm.set(sk,s)}s.items.push(r);s.bytes+=Number(r.item.bytes)||0;var vn=r.volumeNo||'0',v=s.volumes.get(vn);if(!v){v={name:r.volumeNo?'Cilt '+r.volumeNo:'Diğer',no:r.volumeNo,items:[],bytes:0,page:null,chapters:[]};s.volumes.set(vn,v)}v.items.push(r);v.bytes+=Number(r.item.bytes)||0;if(r.kind==='volume')v.page=r;else if(r.kind==='chapter')v.chapters.push(r)});return Array.from(sm.values()).sort(function(a,b){if(a.name==='Diğer')return 1;if(b.name==='Diğer')return-1;return a.name.localeCompare(b.name,'tr')})}
function killOld(){['nava-offline-browser-v12149','nava-offline-browser-v12162'].forEach(function(id){var x=d.getElementById(id);if(x){x.hidden=true;x.style.display='none'}})}
function shell(){killOld();var s=d.getElementById('nava-offline-browser-v12163');if(s)return s;s=el('section','nava-offline-browser-v12163');s.id='nava-offline-browser-v12163';s.hidden=true;s.innerHTML='<header class="nava-offline63-head"><button type="button" data-close aria-label="Kapat">‹</button><div><strong>İndirilenler</strong><span data-summary></span></div></header><div class="nava-offline63-search"><input type="search" data-search autocomplete="off" placeholder="Eser veya bölüm ara"></div><div class="nava-offline63-tree" data-tree></div>';s.querySelector('[data-close]').onclick=hide;s.querySelector('[data-search]').oninput=render;d.body.append(s);return s}
function show(){killOld();var s=shell();s.hidden=false;d.documentElement.classList.add('nava-offline63-open');render()}
function hide(){var s=d.getElementById('nava-offline-browser-v12163');if(s)s.hidden=true;d.documentElement.classList.remove('nava-offline63-open')}
function openUrl(u){if(u)call('open',u)}
function removeOne(r){if(!r||!r.item)return;if(typeof w.confirm==='function'&&!w.confirm('Silinsin mi?'))return;call('delete',r.item.url);setTimeout(render,280)}
function removeMany(rows,label){var seen={},urls=[];(rows||[]).forEach(function(r){var u=r&&r.item&&r.item.url,c=canon(u);if(c&&!seen[c]){seen[c]=1;urls.push(u)}});if(!urls.length)return;if(typeof w.confirm==='function'&&!w.confirm(label+' silinsin mi?'))return;urls.forEach(function(u){call('delete',u)});setTimeout(render,400)}
function groupRow(cls,title,sub,open,toggle,actions){var row=el('div','nava-offline63-group '+cls),left=el('button','nava-offline63-toggle'),chev=el('span','nava-offline63-chev','›'),copy=el('span');left.type='button';left.setAttribute('aria-expanded',open?'true':'false');copy.append(el('strong','',title),el('small','',sub));left.append(chev,copy);left.onclick=toggle;row.append(left);(actions||[]).forEach(function(a){var b=el('button','nava-offline63-action',a.label);b.type='button';b.onclick=function(e){e.stopPropagation();a.run()};row.append(b)});return row}
function chapterRow(r){var row=el('div','nava-offline63-chapter'),b=el('button','nava-offline63-chapter-open'),del=el('button','nava-offline63-delete','×'),title=r.item.title||('Bölüm '+(r.chapterNo||''));b.type=del.type='button';b.append(el('strong','',title),el('small','',r.item.bytes?fmt(r.item.bytes):''));b.onclick=function(){openUrl(r.item.url)};del.onclick=function(e){e.stopPropagation();removeOne(r)};row.append(b,del);return row}
function render(){killOld();var idx=raw(),s=shell(),tree=s.querySelector('[data-tree]'),q=norm(s.querySelector('[data-search]').value),items=idx.items||[];var filtered=q?items.filter(function(i){var r=meta(i);return norm([r.series,i.title,r.volumeTitle,r.volumeNo,r.chapterNo,slug(i.url)].join(' ')).indexOf(q)>=0}):items,gs=groups(filtered);s.querySelector('[data-summary]').textContent=(items.length?items.length+' içerik':'')+(idx.storageBytes?' • '+fmt(idx.storageBytes):'');tree.replaceChildren();if(!gs.length){var e=el('div','nava-offline63-empty');e.append(el('strong','',items.length?'Sonuç yok':'Henüz indirme yok'),el('span','',items.length?'Aramayı değiştir.':'İndirdiğin ciltler burada görünecek.'));tree.append(e);return}gs.forEach(function(series){var sk=norm(series.name),openS=q?true:!!state.seriesOpen[sk],sec=el('section','nava-offline63-series'),body=el('div','nava-offline63-series-body');body.hidden=!openS;sec.append(groupRow('is-series',series.name,series.volumes.size+' cilt',openS,function(){state.seriesOpen[sk]=!state.seriesOpen[sk];render()},[{label:'Sil',run:function(){removeMany(series.items,series.name)}}]));Array.from(series.volumes.values()).sort(function(a,b){return(Number(a.no)||99999)-(Number(b.no)||99999)}).forEach(function(v){var vk=sk+'|'+String(v.no||'0'),openV=q?true:!!state.volumeOpen[vk],vsec=el('section','nava-offline63-volume'),vb=el('div','nava-offline63-volume-body'),acts=[];vb.hidden=!openV;if(v.page)acts.push({label:'Aç',run:function(){openUrl(v.page.item.url)}});acts.push({label:'Sil',run:function(){removeMany(v.items,series.name+' • '+v.name)}});vsec.append(groupRow('is-volume',v.name,v.chapters.length+' bölüm',openV,function(){state.volumeOpen[vk]=!state.volumeOpen[vk];render()},acts));v.chapters.sort(function(a,b){return(Number(a.chapterNo)||999999)-(Number(b.chapterNo)||999999)}).forEach(function(r){vb.append(chapterRow(r))});vsec.append(vb);body.append(vsec)});sec.append(body);tree.append(sec)})}
var prev=w.navaOfflineNativeEvent;w.navaOfflineNativeEvent=function(ev){try{if(typeof prev==='function')prev(ev)}catch(_){}var t=String(ev&&ev.type||'');if(/^(deleted|complete|batch-complete|error|cancelled)$/.test(t))setTimeout(render,0)};
w.navaOpenDownloads=show;
d.addEventListener('click',function(e){var t=e.target&&e.target.closest?e.target.closest('[data-open-library]'):null;if(t)setTimeout(show,0)},true);
var mo=new MutationObserver(function(){if(!shell().hidden)killOld()});if(d.documentElement)mo.observe(d.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden','style']});
if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',shell,{once:true});else shell();
})(document,window);
