import assert from 'node:assert/strict';
await import('../android-patch/v12.1.68/library-core-v12168.js');
await import('../android-patch/v12.1.68/language-core-v12168.js');
const lib=globalThis.NavaLibraryCoreV12168,lang=globalThis.NavaLanguageCoreV12168;
const SERIES='Tensei Shitara Slime Datta Ken (Light Novel)';
const VURL='https://www.verudanava.com/2026/07/tensura-cilt-11.html';
const TR1='https://www.verudanava.com/2026/07/tensura-cilt-11-bolum-1.html';
const EN1='https://www.verudanava.com/2026/07/tensura-cilt-11-bolum-1-en.html';
const TR2='https://www.verudanava.com/2026/07/tensura-cilt-11-bolum-2.html';
function entry(title,url,labels){return{title:{$t:title},link:[{rel:'alternate',href:url}],category:(labels||[]).map(term=>({term}))}}
const volumes=[entry('Tensura Cilt 11',VURL,['Cilt',SERIES,'Tensura Cilt 11'])];
const chapters=[entry('Tensura Cilt 11 Bölüm 1',TR1,['Bölüm','Tensura Cilt 11','TR']),entry('Tensura Cilt 11 Bölüm 1',EN1,['Bölüm','Tensura Cilt 11','EN']),entry('Tensura Cilt 11 Bölüm 2',TR2,['Bölüm','Tensura Cilt 11'])];
assert.strictEqual(lib.clean({foo:'bar'}),'','unknown objects must never stringify to [object Object]');
assert.strictEqual(lib.clean({title:{$t:SERIES}}),SERIES);
const rel=lib.buildRelations(volumes,chapters);
const dirtyRel=structuredClone(rel);
dirtyRel.byUrl[lib.canon(VURL)]={series:{title:{$t:SERIES}},volumeNo:'11',kind:'volume'};
dirtyRel.byAlias[lib.norm('Tensura')]={series:SERIES};
const groups=lib.groupDownloads([{url:VURL,title:'Cilt 11',seriesTitle:{title:{$t:'Tensura Cilt 11'}},kind:'volume'},{url:TR1,title:'Bölüm 1',seriesTitle:'Tensura',kind:'chapter'}],dirtyRel);
assert.strictEqual(groups.length,1);
assert.strictEqual(groups[0].name,SERIES,'object-valued legacy cache must resolve to real work title');
assert(!/object object/i.test(groups[0].name),'[object Object] must never reach UI');
const idx=lang.buildIndex(chapters);
const explicitTr=lang.variantsForUrl(idx,TR1);
assert.deepStrictEqual(explicitTr.languages,['TR','EN']);
assert.strictEqual(explicitTr.show,true,'explicit TR + EN must show selector');
const explicitOnly=lang.buildIndex([entry('Tensura Cilt 11 Bölüm 3','https://www.verudanava.com/2026/07/tensura-cilt-11-bolum-3.html',['Bölüm','Tensura Cilt 11','TR'])]);
const exOnly=lang.variantsForUrl(explicitOnly,'https://www.verudanava.com/2026/07/tensura-cilt-11-bolum-3.html');
assert.deepStrictEqual(exOnly.languages,['TR']);
assert.strictEqual(exOnly.show,true,'explicit TR label must show TR even when it is the only language');
const implicitOnly=lang.buildIndex([entry('Tensura Cilt 11 Bölüm 4','https://www.verudanava.com/2026/07/tensura-cilt-11-bolum-4.html',['Bölüm','Tensura Cilt 11'])]);
const imOnly=lang.variantsForUrl(implicitOnly,'https://www.verudanava.com/2026/07/tensura-cilt-11-bolum-4.html');
assert.deepStrictEqual(imOnly.languages,['TR']);
assert.strictEqual(imOnly.show,false,'implicit/default TR-only chapter stays hidden');
console.log('PASS object-safe offline title: no [object Object]');
console.log('PASS language visibility: explicit TR shows; implicit TR-only hides');
