/* Nava Android 12.1.47 — work language filter TR/EN/JP/KR/CN. */
;(function(d,w){
'use strict';if(w.__navaLanguageV12147)return;w.__navaLanguageV12147=true;if(!w.__NAVA_ANDROID_APP__)return;
var KEY='nava_language_filter_v12147',allowed=['Tümü','TR','EN','JP','KR','CN'],selected='Tümü',map=Object.create(null),loading=false,loaded=false,observer=null,queued=false;
try{var saved=localStorage.getItem(KEY);if(allowed.indexOf(saved)>=0)selected=saved}catch(_){}
function clean(v,n){return String(v==null?'':v).replace(/\s+/g,' ').trim().slice(0,n||500)}function canon(v){try{var u=new URL(String(v||''),location.href);u.hash='';u.protocol='https:';u.hostname='www.verudanava.com';u.port='';return u.href.replace(/\/$/,'')}catch(_){return''}}function labels(en){return(en&&en.category||[]).map(function(x){return clean(x.term,80)}).filter(Boolean)}function href(en){var a=en&&en.link||[];for(var i=0;i<a.length;i++)if(a[i].rel==='alternate'&&a[i].href)return a[i].href;return''}function lang(en){var ls=labels(en);for(var i=0;i<ls.length;i++)if(['TR','EN','JP','KR','CN'].indexOf(ls[i])>=0)return ls[i];return''}
function load(){if(loading||loaded)return Promise.resolve();loading=true;return fetch('/feeds/posts/summary/-/Series?alt=json&max-results=150',{credentials:'same-origin',cache:'no-store'}).then(function(r){if(!r.ok)throw Error('feed');return r.json()}).then(function(j){(j&&j.feed&&j.feed.entry||[]).forEach(function(en){var u=canon(href(en)),l=lang(en);if(u&&l)map[u]=l});loaded=true}).catch(function(){}).finally(function(){loading=false;apply()})}
function eligible(){return!!(d.body&&(d.body.classList.contains('nava-app-home')||d.body.classList.contains('nava-app-discover')))}function bar(){var x=d.getElementById('nava-language-filter-v12147');if(x)return x;var page=d.getElementById('nava-app-page');if(!page||!eligible())return null;x=d.createElement('section');x.id='nava-language-filter-v12147';x.className='nava-language-filter-v12147';x.innerHTML='<span>Dil</span><div></div>';var list=x.lastElementChild;allowed.forEach(function(code){var b=d.createElement('button');b.type='button';b.textContent=code;b.dataset.lang=code;b.onclick=function(){selected=code;try{localStorage.setItem(KEY,code)}catch(_){}syncButtons();apply()};list.append(b)});page.insertBefore(x,page.firstChild);syncButtons();return x}function syncButtons(){var x=d.getElementById('nava-language-filter-v12147');if(!x)return;x.querySelectorAll('button[data-lang]').forEach(function(b){var on=b.dataset.lang===selected;b.classList.toggle('is-active',on);b.setAttribute('aria-pressed',on?'true':'false')})}
function cardLang(card){var u=canon(card.getAttribute('href')||card.href),l=map[u]||'';if(!l){var text=clean(card.textContent,600),m=text.match(/(?:^|\s)(TR|EN|JP|KR|CN)(?:\s|$)/);l=m?m[1]:''}return l}function decorate(card,l){card.dataset.navaLang=l||'';var badge=card.querySelector('.nava-series-lang-v12147');if(!l){if(badge)badge.remove();return}if(!badge){badge=d.createElement('span');badge.className='nava-series-lang-v12147';var cover=card.querySelector('.nava-series-cover-wrap-v2');(cover||card).append(badge)}badge.textContent=l}
function apply(){var x=bar();if(!eligible()){if(x)x.remove();return}if(!x)return;syncButtons();var cards=[].slice.call(d.querySelectorAll('.nava-series-card-v2[href]'));cards.forEach(function(card){var l=cardLang(card);decorate(card,l);card.hidden=selected!=='Tümü'&&l!==selected});var sections=[].slice.call(d.querySelectorAll('#nava-app-page .nava-app-section'));sections.forEach(function(sec){var cs=[].slice.call(sec.querySelectorAll('.nava-series-card-v2[href]'));if(!cs.length)return;sec.classList.toggle('nava-lang-empty-v12147',selected!=='Tümü'&&!cs.some(function(c){return!c.hidden}))})}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(function(){queued=false;apply()})}function init(){bar();load();apply();if(d.body&&!observer){observer=new MutationObserver(schedule);observer.observe(d.body,{childList:true,subtree:true})}w.addEventListener('pageshow',function(){setTimeout(schedule,0);setTimeout(schedule,400)},{passive:true})}if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(document,window);