/* Nava Web 12.3.11-live.1 — shared language variants + reliable notification deletion. */
;(function(d,w){
'use strict';
if(w.__NAVA_WEB_CORE_12311__)return;w.__NAVA_WEB_CORE_12311__=true;

var LANGS=['TR','EN','JP','KR','CN'];
var LANG_PREFIX='nava_series_language_web_v1:';
var feedMap=Object.create(null),feedLoaded=false,feedLoading=null,observer=null,queued=false;
var notify={db:null,auth:null,unsub:null,docs:[],uid:'',observer:null,timer:0};

function clean(v,n){return String(v==null?'':v).replace(/\s+/g,' ').trim().slice(0,n||500)}
function canon(v){try{var u=new URL(String(v||''),location.href);u.hash='';u.protocol='https:';if(/(^|\.)verudanava\.(?:com|blogspot\.com)$/i.test(u.hostname))u.hostname='www.verudanava.com';u.port='';return u.href.replace(/\/$/,'')}catch(_){return''}}
function stripVolume(v){return clean(v,500).replace(/\s+(?:cilt|volume|vol\.?)\s*\d+(?:\.\d+)?(?:\s.*)?$/i,'').trim()}
function volumeNo(v){var m=clean(v,1000).match(/(?:cilt|volume|vol\.?)\s*([0-9]+(?:\.[0-9]+)?)/i);return m?m[1]:''}
function chapterNo(v){var m=clean(v,1000).match(/(?:bölüm|bolum|chapter|ch\.?|episode|ep\.?)\s*([0-9]+(?:\.[0-9]+)?)/i);return m?m[1]:''}
function pageTitle(){var x=d.querySelector('.nava-reader-title-v2,header h1[itemprop="name"],main h1,h1');return clean(x?x.textContent:d.title,350)}
function isReader(){return!!d.getElementById('nava-reader-settings-v2')||!!d.getElementById('nava-reader-chapters-v9')||!!d.querySelector('[data-nava-chapter-meta]')||!!(d.body&&d.body.classList.contains('nava-app-reader'))}
function hasChapterList(){return!!d.querySelector('#clwd,#chapters,[data-nava-chapter-list],.eplister,#nava-reader-chapters-v9')}
function isSeries(){return!!(d.body&&d.body.classList.contains('nava-app-series'))||(!isReader()&&!!d.querySelector('button,a')&&/bölüm listesi/i.test(clean(d.body&&d.body.textContent,3000))&&!!d.querySelector('a[href]'))}
function isVolume(){if(isReader())return false;if(d.body&&d.body.classList.contains('nava-app-volume'))return true;return hasChapterList()&&!!volumeNo(pageTitle()+' '+clean(d.title,300))}
function seriesName(){var meta=d.querySelector('[data-nava-chapter-meta]'),v=clean(meta&&meta.getAttribute('data-volume-title'),450);if(v)return stripVolume(v);var tags=[].slice.call(d.querySelectorAll('a[rel="tag"]')).map(function(a){return clean(a.textContent,300)}).filter(function(x){return/(?:cilt|volume|vol\.?)\s*\d/i.test(x)});if(tags[0])return stripVolume(tags[0]);var h=pageTitle();return stripVolume(h.replace(/\s*\|\s*Nava\s*$/i,''))}
function seriesKey(name){return clean(name||seriesName(),350).toLocaleLowerCase('tr-TR').replace(/\s+/g,' ')}
function storageKey(name){return LANG_PREFIX+seriesKey(name)}
function getSelected(name,available){var saved='';try{saved=localStorage.getItem(storageKey(name))||''}catch(_){}if(available&&available.length){if(available.indexOf(saved)>=0)return saved;if(available.indexOf('TR')>=0)return'TR';return available[0]}return LANGS.indexOf(saved)>=0?saved:'TR'}
function setSelected(name,lang){lang=clean(lang,10).toUpperCase();if(LANGS.indexOf(lang)<0)return;try{localStorage.setItem(storageKey(name),lang)}catch(_){}schedule()}

function labels(en){return(en&&en.category||[]).map(function(x){return clean(x.term,100)}).filter(Boolean)}
function href(en){var a=en&&en.link||[];for(var i=0;i<a.length;i++)if(a[i].rel==='alternate'&&a[i].href)return a[i].href;return''}
function langFromLabels(ls){for(var i=0;i<ls.length;i++){var u=clean(ls[i],10).toUpperCase();if(LANGS.indexOf(u)>=0)return u}return''}
function feedPage(start){return fetch('/feeds/posts/summary?alt=json&max-results=500&start-index='+start,{credentials:'same-origin',cache:'no-store'}).then(function(r){if(!r.ok)throw Error('feed '+r.status);return r.json()})}
function readyLanguages(){if(feedLoaded)return Promise.resolve(feedMap);if(feedLoading)return feedLoading;feedLoading=(async function(){try{for(var start=1,pass=0;pass<6;start+=500,pass++){var j=await feedPage(start),entries=j&&j.feed&&j.feed.entry||[];entries.forEach(function(en){var u=canon(href(en)),l=langFromLabels(labels(en));if(u&&l)feedMap[u]=l});if(entries.length<500)break}}catch(e){try{console.warn('Nava dil verisi alınamadı',e)}catch(_){}}feedLoaded=true;feedLoading=null;schedule();return feedMap})();return feedLoading}

function rowFor(a){return a.closest('li,article,[data-nava-chapter],.nava-chapter-item,.chapter-item,.eplister li,.eplister ul>li,#nava-reader-chapters-v9 li,.nava-reader-chapter-row')||a.parentElement||a}
function rowVolume(row){var text=clean(row&&row.textContent,1000),v=volumeNo(text);if(v)return v;var p=row&&row.closest('[data-volume-title],[data-nava-volume],section,article,.bixbox,.eplister');if(p){v=volumeNo(clean((p.getAttribute&&p.getAttribute('data-volume-title'))||'',300)+' '+clean(p.textContent,1500));if(v)return v}var meta=d.querySelector('[data-nava-chapter-meta]');return volumeNo(clean(meta&&meta.getAttribute('data-volume-title'),350))}
function chapterAnchors(root){root=root||d;var seen=new Set(),out=[];[].slice.call(root.querySelectorAll('#clwd a[href],#chapters a[href],[data-nava-chapter-list] a[href],.eplister a[href],#nava-reader-chapters-v9 a[href]')).forEach(function(a){var u=canon(a.href),row=rowFor(a),text=clean((row||a).textContent,1000),n=chapterNo(clean(a.textContent,300)+' '+text),v=rowVolume(row);if(!u||!n||seen.has(u))return;seen.add(u);out.push({a:a,row:row,url:u,no:n,volume:v,lang:feedMap[u]||''})});return out}
function availableFor(items){var s=new Set();items.forEach(function(x){if(LANGS.indexOf(x.lang)>=0)s.add(x.lang)});var current=feedMap[canon(location.href)]||'';if(current)s.add(current);return LANGS.filter(function(l){return s.has(l)})}
function chooseGroup(group,selected){var exact=group.filter(function(x){return x.lang===selected})[0];if(exact)return exact;var tr=group.filter(function(x){return x.lang==='TR'})[0];return tr||group[0]}
function groupKey(x){return(x.volume||'current')+'|'+x.no}
function currentIdentity(items){var url=canon(location.href),hit=items.filter(function(x){return x.url===url})[0];if(hit)return{no:hit.no,volume:hit.volume,url:hit.url};var meta=d.querySelector('[data-nava-chapter-meta]'),v=volumeNo(clean(meta&&meta.getAttribute('data-volume-title'),400)),n=chapterNo(pageTitle()+' '+clean(d.title,350));return{no:n,volume:v,url:url}}
function navigateCurrentVariant(lang,items){var cur=currentIdentity(items);if(!cur.no)return;var same=items.filter(function(x){return x.no===cur.no&&(!cur.volume||!x.volume||x.volume===cur.volume)}),target=same.filter(function(x){return x.lang===lang})[0];if(target&&target.url&&target.url!==cur.url)location.assign(target.url)}

function renderReaderLanguage(items){var old=d.getElementById('nava-web-reader-language-v1');if(!isReader()){if(old)old.remove();return}var panel=d.getElementById('nava-reader-settings-v2');if(!panel){if(old)old.remove();return}var avail=availableFor(items);if(!avail.length){if(old)old.remove();return}var name=seriesName(),selected=getSelected(name,avail);if(!old){old=d.createElement('section');old.id='nava-web-reader-language-v1';old.className='nava-web-reader-language-v1';old.innerHTML='<div class="nava-web-reader-language-copy"><strong>Dil</strong><small>Bu eser için</small></div><div class="nava-web-reader-language-options"></div>';panel.append(old)}else if(old.parentNode!==panel)panel.append(old);var sig=selected+'|'+avail.join(',');if(old.dataset.sig===sig)return;old.dataset.sig=sig;var list=old.querySelector('.nava-web-reader-language-options');list.replaceChildren();avail.forEach(function(l){var b=d.createElement('button');b.type='button';b.textContent=l;b.dataset.lang=l;var on=l===selected;b.classList.toggle('is-active',on);b.setAttribute('aria-pressed',on?'true':'false');b.onclick=function(e){e.preventDefault();e.stopPropagation();setSelected(name,l);navigateCurrentVariant(l,items)};list.append(b)})}
function applyLanguageList(items){if(!(isSeries()||isVolume()))return;if(!items.length)return;var avail=availableFor(items),selected=getSelected(seriesName(),avail),groups=new Map();items.forEach(function(x){var k=groupKey(x);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(x)});groups.forEach(function(g){var chosen=chooseGroup(g,selected);g.forEach(function(x){if(x.row){var hide=x!==chosen;if(x.row.hidden!==hide)x.row.hidden=hide}})})}
function applyLanguages(){var items=chapterAnchors(d);applyLanguageList(items);renderReaderLanguage(items)}

function notifyReady(){notify.db=w.db||notify.db;notify.auth=w.auth||notify.auth;return!!(notify.db&&notify.auth&&w.firebase)}
function notifyUser(){try{return notify.auth&&notify.auth.currentUser}catch(_){return null}}
function notifyCol(){var u=notifyUser();return u&&notify.db?notify.db.collection('users').doc(u.uid).collection('notifications'):null}
function notifyMs(v){try{if(v&&typeof v.toMillis==='function')return v.toMillis();if(v&&typeof v.toDate==='function')return v.toDate().getTime();return new Date(v||0).getTime()||0}catch(_){return 0}}
function notifyGroups(items){var out=[],likes=new Map();(items||[]).forEach(function(i){if(i.type!=='like'){out.push({items:[i],latest:i});return}var k='like:'+clean(i.postId,200)+':'+clean(i.commentId,200);if(!likes.has(k)){var g={items:[],latest:i};likes.set(k,g);out.push(g)}var c=likes.get(k);c.items.push(i);if(notifyMs(i.createdAt)>notifyMs(c.latest.createdAt))c.latest=i});out.sort(function(a,b){return notifyMs(b.latest.createdAt)-notifyMs(a.latest.createdAt)});return out}
function mapNotificationIds(){var list=d.getElementById('nava-notification-list');if(!list)return;var cards=[].slice.call(list.querySelectorAll('.nava-notification-item')),groups=notifyGroups(notify.docs);cards.forEach(function(card,i){if(groups[i])card.dataset.navaNotificationIds=groups[i].items.map(function(x){return x.id}).filter(Boolean).join(',');else delete card.dataset.navaNotificationIds})}
async function deleteNotificationIds(ids){var c=notifyCol();if(!c)throw new Error('Oturum yok');var unique=Array.from(new Set((ids||[]).map(function(x){return clean(x,240)}).filter(Boolean)));for(var i=0;i<unique.length;i+=400){var batch=notify.db.batch();unique.slice(i,i+400).forEach(function(id){batch.delete(c.doc(id))});await batch.commit()}return unique.length}
async function clearAllNotifications(){var c=notifyCol();if(!c)throw new Error('Oturum yok');var removed=0;for(var pass=0;pass<30;pass++){var snap=await c.limit(400).get();if(snap.empty)break;var batch=notify.db.batch();snap.docs.forEach(function(x){batch.delete(x.ref)});await batch.commit();removed+=snap.size;if(snap.size<400)break}return removed}
function wireNotifications(){var panel=d.getElementById('nava-notification-panel'),actions=panel&&panel.querySelector('.nava-notification-head-actions'),list=d.getElementById('nava-notification-list');if(!panel||!actions||!list)return false;var oldRead=d.getElementById('nava-notification-clear-read');if(oldRead&&!oldRead.hidden){oldRead.hidden=true;oldRead.style.display='none'}var oldSeen=[].slice.call(actions.querySelectorAll('button')).filter(function(b){return/okunanları temizle|tümünü okundu yap/i.test(clean(b.textContent,80))});oldSeen.forEach(function(b){if(!b.hidden){b.hidden=true;b.style.display='none'}});var btn=d.getElementById('nava-notification-clear-all-web-v1');if(!btn){btn=d.createElement('button');btn.type='button';btn.id='nava-notification-clear-all-web-v1';btn.className='nava-notification-head-button';btn.textContent='Tümünü temizle';btn.setAttribute('aria-label','Tüm bildirimleri temizle');btn.onclick=function(e){e.preventDefault();e.stopPropagation();if(btn.disabled)return;btn.disabled=true;btn.textContent='Temizleniyor…';clearAllNotifications().then(function(n){btn.textContent=n?'Temizlendi':'Bildirim yok'}).catch(function(err){try{console.error('Bildirimler temizlenemedi:',err)}catch(_){}btn.textContent='Tekrar dene'}).finally(function(){setTimeout(function(){btn.disabled=false;btn.textContent='Tümünü temizle'},1200)})};actions.append(btn)}if(panel.dataset.navaWebDeleteFix!=='1'){panel.dataset.navaWebDeleteFix='1';panel.addEventListener('click',function(e){var del=e.target&&e.target.closest?e.target.closest('.nava-notification-delete'):null;if(!del)return;var card=del.closest('.nava-notification-item'),raw=card&&card.dataset.navaNotificationIds;if(!raw)return;var ids=raw.split(',').map(function(x){return clean(x,240)}).filter(Boolean);if(!ids.length)return;e.preventDefault();e.stopImmediatePropagation();del.disabled=true;deleteNotificationIds(ids).catch(function(err){try{console.error('Bildirim silinemedi:',err)}catch(_){}del.disabled=false})},true)}if(list.dataset.navaWebDeleteMap!=='1'){list.dataset.navaWebDeleteMap='1';new MutationObserver(function(){setTimeout(mapNotificationIds,0)}).observe(list,{childList:true,subtree:true})}mapNotificationIds();return true}
function subscribeNotifications(user){if(notify.unsub){try{notify.unsub()}catch(_){}notify.unsub=null}notify.docs=[];notify.uid=user&&user.uid||'';mapNotificationIds();if(!user)return;notify.unsub=notify.db.collection('users').doc(user.uid).collection('notifications').orderBy('createdAt','desc').limit(80).onSnapshot(function(s){notify.docs=s.docs.map(function(x){return Object.assign({id:x.id},x.data()||{})});setTimeout(function(){wireNotifications();mapNotificationIds()},0)},function(err){try{console.error('Bildirim dinleyicisi:',err)}catch(_){}})}
function startNotifications(){if(!notifyReady()){clearTimeout(notify.timer);notify.timer=setTimeout(startNotifications,300);return}if(!notify.bound){notify.bound=true;notify.auth.onAuthStateChanged(subscribeNotifications)}wireNotifications();if(!notify.observer&&d.body){notify.observer=new MutationObserver(function(){wireNotifications();var u=notifyUser(),uid=u&&u.uid||'';if(uid!==notify.uid)subscribeNotifications(u)});notify.observer.observe(d.body,{childList:true,subtree:true})}}

function cleanupLegacy(){['nava-loader-v2-test','nava-live-connection-test','nava-series-language-v12149'].forEach(function(id){var x=d.getElementById(id);if(x)try{x.remove()}catch(_){}});d.documentElement.setAttribute('data-nava-live-version','12.3.11-live.1')}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(function(){queued=false;cleanupLegacy();applyLanguages();wireNotifications()})}
function init(){cleanupLegacy();if(isReader()||isSeries()||isVolume()||hasChapterList())readyLanguages().then(schedule);startNotifications();schedule();if(d.body&&!observer){observer=new MutationObserver(schedule);observer.observe(d.body,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden','class']})}w.addEventListener('pageshow',function(){setTimeout(schedule,0);setTimeout(schedule,500)},{passive:true})}

w.NavaWebLanguage={ready:readyLanguages,getLanguage:function(url){return feedMap[canon(url)]||''},getSelected:getSelected,setSelected:setSelected};
if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(document,window);
