/* Nava Android 12.1.56 — visible picker footer + strict queue/download de-duplication. */
;(function(d,w){
'use strict';
if(w.__navaPickerPolishV12156)return;w.__navaPickerPolishV12156=true;
var PICKER='#nava-series-download-picker-v12155',QUEUE_KEY='nava_download_queue_v12149',busy=false,cache={};
function clean(v,n){return String(v==null?'':v).replace(/\s+/g,' ').trim().slice(0,n||500)}
function canon(v){try{var u=new URL(String(v||''),location.href);if(!/(^|\.)verudanava\.(?:com|blogspot\.com)$/i.test(u.hostname))return'';u.hash='';u.protocol='https:';u.hostname='www.verudanava.com';u.port='';return u.href}catch(_){return''}}
function norm(v){return clean(v,700).toLocaleLowerCase('tr-TR').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ')}
function entryLink(e){var a=(e&&e.link||[]).find(function(x){return x&&x.rel==='alternate'&&x.href});return canon(a&&a.href)}
function entryLabels(e){return(e&&e.category||[]).map(function(x){return clean(x&&x.term,400)}).filter(Boolean)}
function entryTitle(e){return clean(e&&e.title&&e.title.$t,500)}
function hasLabel(e,label){var n=norm(label);return!!n&&entryLabels(e).some(function(x){return norm(x)===n})}
function chapterNo(v){var m=clean(v,900).match(/(?:bölüm|bolum|chapter|ch\.?|episode|ep\.?)\s*([0-9]+(?:\.[0-9]+)?)/i);return m?m[1]:''}
function isChapter(e){return hasLabel(e,'Bölüm')||hasLabel(e,'Chapter')||!!chapterNo(entryTitle(e))}
async function feed(label){var k=norm(label),hit=cache[k];if(hit&&Date.now()-hit.at<90000)return hit.entries;var out=[],start=1,size=500;for(var p=0;p<6;p++){var url='https://www.verudanava.com/feeds/posts/summary/-/'+encodeURIComponent(label)+'?alt=json&start-index='+start+'&max-results='+size+'&orderby=published&_nava56='+Date.now();var r=await fetch(url,{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw new Error('Feed HTTP '+r.status+' • '+label);var j=await r.json(),arr=j&&j.feed&&j.feed.entry||[];out=out.concat(arr);if(arr.length<size)break;start+=size}cache[k]={at:Date.now(),entries:out};return out}
function stripDebug(s){return clean(s,500).replace(/^12\.1\.55\s*•\s*/,'')}
function polish(q){if(!q)return;var sub=q.querySelector('header span');if(sub)sub.textContent='Ciltleri seç';var st=q.querySelector('[data-picker-status]');if(st){var fix=function(){var x=stripDebug(st.textContent);if(x!==st.textContent)st.textContent=x};fix();if(!st.__nava56obs){st.__nava56obs=new MutationObserver(fix);st.__nava56obs.observe(st,{childList:true,characterData:true,subtree:true})}}var f=q.querySelector('footer');if(f)f.setAttribute('data-nava56-footer','1')}
function setStatus(q,text,err){var x=q&&q.querySelector('[data-picker-status]');if(!x)return;x.textContent=text||'';x.className='nava-series-download-picker-status-v12149'+(err?' is-error':'')}
function sync(q){var n=q.querySelectorAll('input[type=checkbox]:checked').length,b=q.querySelector('[data-start]');if(b){b.textContent=n?('Seçilenleri indir ('+n+')'):'Cilt seç';b.disabled=!n||busy}}
function downloadedSet(){var m={};try{var j=JSON.parse(w.NavaOffline&&w.NavaOffline.listDownloads?w.NavaOffline.listDownloads():'{}');(j.items||[]).forEach(function(x){var u=canon(x&&x.url);if(u)m[u]=1})}catch(_){}return m}
function queueState(){var arr=[];try{arr=JSON.parse(localStorage.getItem(QUEUE_KEY)||'[]');if(!Array.isArray(arr))arr=[]}catch(_){arr=[]}return arr}
function blockedSet(){var m=downloadedSet();queueState().forEach(function(x){var u=canon(x&&x.url),s=clean(x&&x.status,30).toLowerCase();if(u&&s!=='error')m[u]=1});return m}
function saveFresh(items){var q=queueState(),map={};q.forEach(function(x){var u=canon(x&&x.url);if(u)map[u]=x});items.forEach(function(x){var u=canon(x&&x.url);if(!u||map[u])return;map[u]={url:u,title:clean(x.title,220)||'İçerik',seriesTitle:clean(x.seriesTitle,300),kind:clean(x.kind,30)||'chapter',status:'waiting',done:0,total:0,message:''}});try{localStorage.setItem(QUEUE_KEY,JSON.stringify(Object.keys(map).map(function(k){return map[k]}).slice(0,900)))}catch(_){}}
function chaptersFor(v,entries,info){var label=clean(v&&v.volumeLabel,400),seen={},out=[];if(!label)return out;(entries||[]).forEach(function(e){if(!isChapter(e)||!hasLabel(e,label))return;var u=entryLink(e),n=chapterNo(entryTitle(e));if(!n){var labs=entryLabels(e);for(var i=0;i<labs.length&&!n;i++)n=chapterNo(labs[i])}if(!u||!n||seen[u])return;seen[u]=1;out.push({url:u,title:entryTitle(e)||('Bölüm '+n),seriesTitle:info.title+' Cilt '+v.volumeNo,kind:'chapter',chapterNo:n})});out.sort(function(a,b){return(Number(a.chapterNo)||999999)-(Number(b.chapterNo)||999999)});return out}
async function languageFilter(items,series){var api=w.NavaSeriesLanguageV12149;if(!api||typeof api.ready!=='function'||typeof api.filterDownloadItems!=='function')return items;try{await api.ready();return await api.filterDownloadItems(items,series)}catch(_){return items}}
async function start(q){if(busy)return;polish(q);var info=q.__seriesInfo,vols=q.__volumes||[],picked=[];vols.forEach(function(v,i){var cb=q.querySelector('input[data-index="'+i+'"]');if(cb&&cb.checked)picked.push(v)});if(!info||!picked.length){setStatus(q,'Önce en az bir cilt seç.',true);return}if(!w.NavaOffline||typeof w.NavaOffline.downloadBatch!=='function'){setStatus(q,'Native indirme hazır değil.',true);return}busy=true;sync(q);try{setStatus(q,'Bölümler hazırlanıyor...');var chapters=await feed('Bölüm'),blocked=blockedSet(),fresh=[],inBatch={},volumeCount=0,chapterCount=0;for(var i=0;i<picked.length;i++){var v=picked[i],vu=canon(v.postUrl);if(vu&&!blocked[vu]&&!inBatch[vu]){inBatch[vu]=1;fresh.push({url:vu,title:'Cilt '+v.volumeNo,seriesTitle:info.title+' Cilt '+v.volumeNo,kind:'volume'});volumeCount++}var got=await languageFilter(chaptersFor(v,chapters,info),info.title);got.forEach(function(x){var u=canon(x.url);if(!u||blocked[u]||inBatch[u])return;inBatch[u]=1;fresh.push(x);chapterCount++})}if(!fresh.length){setStatus(q,'Seçilen içerikler zaten indirildi veya indirme sırasında.');return}fresh=fresh.slice(0,900);saveFresh(fresh);var r=w.NavaOffline.downloadBatch(JSON.stringify(fresh));if(r===false)throw new Error('Native downloadBatch reddetti');setStatus(q,volumeCount+' cilt + '+chapterCount+' bölüm indirme sırasına eklendi.');setTimeout(function(){q.hidden=true;var top=d.getElementById('nava-download-top-v12149');if(top)top.click()},650)}catch(err){console.error('Nava 12.1.56 download',err);setStatus(q,'İndirme hazırlanamadı: '+clean(err&&err.message,160),true)}finally{busy=false;sync(q)}}
function interceptStart(e){var b=e.target&&e.target.closest?e.target.closest(PICKER+' [data-start]'):null;if(!b)return;var q=d.querySelector(PICKER);if(!q)return;e.preventDefault();e.stopPropagation();if(typeof e.stopImmediatePropagation==='function')e.stopImmediatePropagation();start(q)}
d.addEventListener('click',interceptStart,true);
var mo=new MutationObserver(function(ms){ms.forEach(function(m){[].slice.call(m.addedNodes||[]).forEach(function(n){if(!n||n.nodeType!==1)return;if(n.matches&&n.matches(PICKER))polish(n);else if(n.querySelector)polish(n.querySelector(PICKER))})});var q=d.querySelector(PICKER);if(q)polish(q)});mo.observe(d.documentElement,{childList:true,subtree:true});var existing=d.querySelector(PICKER);if(existing)polish(existing);
})(document,window);
