/* Nava Android 12.1.66 — current-chapter-only reader language selector. */
;(function(d,w){
'use strict';
var LANGS=['TR','EN','JP','KR','CN'],PREFIX='nava_series_language_v12149:',map=Object.create(null),loaded=false,loading=null,observer=null,queued=false;
function clean(v,n){return String(v==null?'':v).replace(/\s+/g,' ').trim().slice(0,n||500)}
function canon(v){try{var u=new URL(String(v||''),location.href);u.hash='';u.protocol='https:';u.hostname='www.verudanava.com';u.port='';return u.href.replace(/\/$/,'')}catch(_){return''}}
function labels(en){return(en&&en.category||[]).map(function(x){return clean(x.term,100)}).filter(Boolean)}
function href(en){var a=en&&en.link||[];for(var i=0;i<a.length;i++)if(a[i].rel==='alternate'&&a[i].href)return a[i].href;return''}
function langFromLabels(ls){for(var i=0;i<ls.length;i++){var u=clean(ls[i],10).toUpperCase();if(LANGS.indexOf(u)>=0)return u}return''}
function feedPage(start){return fetch('/feeds/posts/summary?alt=json&max-results=500&start-index='+start,{credentials:'same-origin',cache:'no-store'}).then(function(r){if(!r.ok)throw Error('feed '+r.status);return r.json()})}
function ready(){if(loaded)return Promise.resolve(map);if(loading)return loading;loading=(async function(){try{for(var start=1,pass=0;pass<6;start+=500,pass++){var j=await feedPage(start),entries=j&&j.feed&&j.feed.entry||[];entries.forEach(function(en){var u=canon(href(en)),l=langFromLabels(labels(en));if(u&&l)map[u]=l});if(entries.length<500)break}}catch(e){console.warn('Dil verisi alınamadı',e)}loaded=true;loading=null;schedule();return map})();return loading}
function stripVolume(v){return clean(v,400).replace(/\s+(?:cilt|volume|vol\.?)\s*\d+(?:\.\d+)?(?:\s.*)?$/i,'').trim()}
function volumeNo(v){var m=clean(v,800).match(/(?:cilt|volume|vol\.?)\s*([0-9]+(?:\.[0-9]+)?)/i);return m?m[1]:''}
function chapterNo(v){var m=clean(v,800).match(/(?:bölüm|bolum|chapter|ch\.?|episode|ep\.?)\s*([0-9]+(?:\.[0-9]+)?)/i);return m?m[1]:''}
function pageTitle(){var x=d.querySelector('.nava-reader-title-v2,header h1[itemprop="name"],main h1,h1');return clean(x?x.textContent:d.title,300)}
function seriesName(){var body=d.body;if(body&&body.classList.contains('nava-app-series'))return pageTitle();var meta=d.querySelector('[data-nava-chapter-meta]'),v=clean(meta&&meta.getAttribute('data-volume-title'),400);if(v)return stripVolume(v);var tags=[].slice.call(d.querySelectorAll('a[rel="tag"]')).map(function(a){return clean(a.textContent,300)}).filter(function(x){return/(?:cilt|volume|vol\.?)\s*\d/i.test(x)});if(tags[0])return stripVolume(tags[0]);return stripVolume(pageTitle())}
function seriesKey(name){return clean(name||seriesName(),300).toLocaleLowerCase('tr-TR').replace(/\s+/g,' ')}
function storageKey(name){return PREFIX+seriesKey(name)}
function getSelected(name,available){var saved='';try{saved=localStorage.getItem(storageKey(name))||''}catch(_){}if(available&&available.indexOf(saved)>=0)return saved;if(available&&available.indexOf('TR')>=0)return'TR';return available&&available[0]||'TR'}
function setSelected(name,lang){lang=clean(lang,10).toUpperCase();if(LANGS.indexOf(lang)<0)return;try{localStorage.setItem(storageKey(name),lang)}catch(_){}schedule()}
function ensureStyle(){if(d.getElementById('nava-reader-language-style-v12166'))return;var s=d.createElement('style');s.id='nava-reader-language-style-v12166';s.textContent='.nava-reader-language-setting-v12166{box-sizing:border-box;display:grid;grid-template-columns:minmax(90px,.8fr) minmax(0,1.2fr);align-items:center;gap:12px;margin:8px 12px 12px;padding:12px 0 2px;border-top:1px solid rgba(127,145,166,.22);min-width:0}.nava-reader-language-copy-v12166{min-width:0;display:grid;gap:2px}.nava-reader-language-copy-v12166 strong{font-size:12px;font-weight:850}.nava-reader-language-copy-v12166 small{font-size:9.5px;opacity:.62}.nava-reader-language-options-v12166{min-width:0;max-width:100%;width:100%;display:flex;justify-content:flex-start;gap:5px;overflow-x:auto!important;overflow-y:hidden!important;-webkit-overflow-scrolling:touch;overscroll-behavior-x:contain;touch-action:pan-x;scrollbar-width:none;padding-bottom:2px}.nava-reader-language-options-v12166::-webkit-scrollbar{display:none}.nava-reader-language-options-v12166 button{flex:0 0 auto;min-width:42px;min-height:32px;padding:0 10px;border:1px solid #d2dce8;border-radius:8px;background:#f8fafc;color:#5e7087;font:800 10px/1 system-ui,-apple-system,"Segoe UI",sans-serif;touch-action:manipulation}.nava-reader-language-options-v12166 button.is-active{border-color:#7898ba;background:#eaf2fb;color:#466184}html.dark.nava-app-v9 .nava-reader-language-setting-v12166{border-color:#334155}html.dark.nava-app-v9 .nava-reader-language-options-v12166 button{background:#182334;border-color:#35475d;color:#cbd5e1}html.dark.nava-app-v9 .nava-reader-language-options-v12166 button.is-active{background:#213047;border-color:#58789d;color:#c6dafc}@media(max-width:360px){.nava-reader-language-setting-v12166{grid-template-columns:1fr;gap:7px}.nava-reader-language-options-v12166{justify-content:flex-start}}';(d.head||d.documentElement).append(s)}
function rowFor(a){return a.closest('li,article,[data-nava-chapter],.nava-chapter-item,.chapter-item,.eplister li,.eplister ul>li,#nava-reader-chapters-v9 li')||a.parentElement||a}
function chapterAnchors(root){root=root||d;var seen=new Set(),out=[];[].slice.call(root.querySelectorAll('#clwd a[href],#chapters a[href],[data-nava-chapter-list] a[href],.eplister a[href],#nava-reader-chapters-v9 a[href]')).forEach(function(a){var u=canon(a.href),row=rowFor(a),text=clean((row||a).textContent,900),n=chapterNo(clean(a.textContent,250)+' '+text),v=volumeNo(text);if(!u||!n||seen.has(u))return;seen.add(u);out.push({a:a,row:row,url:u,no:n,volume:v,lang:map[u]||''})});return out}
function availableFor(items){var s=new Set();items.forEach(function(x){if(LANGS.indexOf(x.lang)>=0)s.add(x.lang)});return LANGS.filter(function(l){return s.has(l)})}
function chooseGroup(group,selected){var exact=group.filter(function(x){return x.lang===selected})[0];if(exact)return exact;var tr=group.filter(function(x){return x.lang==='TR'})[0];return tr||group[0]}
function groupKey(x){return(x.volume||'current')+'|'+x.no}
function currentIdentity(items){var url=canon(location.href),hit=items.filter(function(x){return x.url===url})[0];if(hit)return{no:hit.no,volume:hit.volume,url:hit.url};var meta=d.querySelector('[data-nava-chapter-meta]'),v=volumeNo(clean(meta&&meta.getAttribute('data-volume-title'),400)),n=chapterNo(pageTitle()+' '+clean(d.title,300));return{no:n,volume:v,url:url}}
function currentAvailable(items){var cur=currentIdentity(items);if(!cur.no)return[];var same=items.filter(function(x){return x.no===cur.no&&(!cur.volume||!x.volume||x.volume===cur.volume)}),s=new Set();same.forEach(function(x){if(LANGS.indexOf(x.lang)>=0)s.add(x.lang)});var currentLang=map[cur.url]||'';if(currentLang)s.add(currentLang);return LANGS.filter(function(l){return s.has(l)})}
function navigateCurrentVariant(lang,items){var cur=currentIdentity(items);if(!cur.no)return;var same=items.filter(function(x){return x.no===cur.no&&(!cur.volume||!x.volume||x.volume===cur.volume)}),target=same.filter(function(x){return x.lang===lang})[0];if(target&&target.url&&target.url!==cur.url)location.assign(target.url)}
function readerSetting(items){var old=d.getElementById('nava-reader-language-v12165');if(old)old.remove();old=d.getElementById('nava-reader-language-v12149');if(old)old.remove();var body=d.body,panel=d.getElementById('nava-reader-settings-v2'),row=d.getElementById('nava-reader-language-v12166');if(!(body&&body.classList.contains('nava-app-reader'))||!panel){if(row)row.remove();return}var avail=currentAvailable(items);if(avail.length<=1){if(row)row.remove();return}var name=seriesName(),selected=getSelected(name,avail);if(!row){row=d.createElement('section');row.id='nava-reader-language-v12166';row.className='nava-reader-language-setting-v12166';row.innerHTML='<div class="nava-reader-language-copy-v12166"><strong>Dil</strong><small>Bu bölüm için</small></div><div class="nava-reader-language-options-v12166"></div>';panel.append(row)}else if(row.parentNode!==panel)panel.append(row);var sig=selected+'|'+avail.join(',');if(row.dataset.sig===sig)return;row.dataset.sig=sig;var list=row.querySelector('.nava-reader-language-options-v12166');list.replaceChildren();avail.forEach(function(l){var b=d.createElement('button');b.type='button';b.textContent=l;b.dataset.lang=l;b.classList.toggle('is-active',l===selected);b.setAttribute('aria-pressed',l===selected?'true':'false');b.onclick=function(e){e.preventDefault();e.stopPropagation();setSelected(name,l);navigateCurrentVariant(l,items)};list.append(b)})}
function applyList(items){if(!(d.body&&(d.body.classList.contains('nava-app-series')||d.body.classList.contains('nava-app-volume')))||!items.length)return;var avail=availableFor(items),selected=getSelected(seriesName(),avail),groups=new Map();items.forEach(function(x){var k=groupKey(x);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(x)});groups.forEach(function(g){var chosen=chooseGroup(g,selected);g.forEach(function(x){if(x.row)x.row.hidden=x!==chosen})})}
function apply(){var standalone=d.getElementById('nava-series-language-v12149');if(standalone)standalone.remove();var items=chapterAnchors(d);applyList(items);readerSetting(items)}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(function(){queued=false;apply()})}
function filterDownloadItems(items,name){items=Array.isArray(items)?items.slice():[];var chapters=items.filter(function(x){return x&&x.kind==='chapter'}),other=items.filter(function(x){return !x||x.kind!=='chapter'});if(!chapters.length)return items;var avail=new Set();chapters.forEach(function(x){var l=map[canon(x.url)]||'';if(l)avail.add(l)});var order=LANGS.filter(function(l){return avail.has(l)}),selected=getSelected(name,order),groups=new Map();chapters.forEach(function(x){var n=x.chapterNo||chapterNo(x.title);if(!n){other.push(x);return}var v=volumeNo(x.seriesTitle||x.title)||'current',k=v+'|'+n;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(x)});groups.forEach(function(g){var exact=g.filter(function(x){return map[canon(x.url)]===selected})[0],tr=g.filter(function(x){return map[canon(x.url)]==='TR'})[0];other.push(exact||tr||g[0])});return other}
w.NavaSeriesLanguageV12149={ready:ready,getLanguage:function(url){return map[canon(url)]||''},getSelected:function(name,available){return getSelected(name,available)},setSelected:setSelected,filterDownloadItems:filterDownloadItems};
function init(){ensureStyle();ready();apply();if(d.body&&!observer){observer=new MutationObserver(schedule);observer.observe(d.body,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden','class']})}w.addEventListener('pageshow',function(){setTimeout(schedule,0);setTimeout(schedule,500)},{passive:true})}
if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(document,window);
