/* Nava Android 12.1.42 — compact reliable download center. */
;(function(d,w){
  'use strict';
  if(w.__navaDownloadMenuV12142)return;
  w.__navaDownloadMenuV12142=true;
  if(!w.__NAVA_ANDROID_APP__||!w.NavaOffline)return;

  var ICON={download:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v11"/><path d="m7.5 10 4.5 4.5 4.5-4.5"/><path d="M5 20h14"/></svg>',folder:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M3 7h7l2 2h9v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z"/></svg>',stack:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="m12 3 8 4-8 4-8-4 8-4Z"/><path d="m4 12 8 4 8-4"/><path d="m4 17 8 4 8-4"/></svg>',book:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v16H6.5A2.5 2.5 0 0 0 4 21.5v-16Z"/><path d="M4 18.5A2.5 2.5 0 0 1 6.5 16H20"/></svg>'};
  var busy=false,observer=null,prevNative=w.navaOfflineNativeEvent||null;

  function clean(v,n){return String(v==null?'':v).replace(/\s+/g,' ').trim().slice(0,n||500)}
  function el(tag,cls,text){var x=d.createElement(tag);if(cls)x.className=cls;if(text!=null)x.textContent=text;return x}
  function call(method){try{var fn=w.NavaOffline&&w.NavaOffline[method];if(typeof fn!=='function')return null;return fn.apply(w.NavaOffline,[].slice.call(arguments,1))}catch(_){return null}}
  function canonical(value){try{var u=new URL(String(value||''),location.href);if(!/^https?:$/.test(u.protocol))return'';var h=(u.hostname||'').toLowerCase();if(h!=='verudanava.com'&&h!=='www.verudanava.com'&&h!=='verudanava.blogspot.com')return'';u.protocol='https:';u.hostname='www.verudanava.com';u.port='';u.hash='';return u.href}catch(_){return''}}
  function currentUrl(){return canonical(location.href)||location.href}
  function isReader(){return !!((d.body&&d.body.classList.contains('nava-app-reader'))||d.querySelector('[data-nava-chapter-meta],#reader,.nava-reader-title-v2'))}
  function pageTitle(root){root=root||d;var x=root.querySelector('.nava-reader-title-v2,header h1[itemprop="name"],main h1,h1');return clean(x?x.textContent:(root===d?d.title:''),300)||'İçerik'}
  function volumeTitle(root){root=root||d;var meta=root.querySelector('[data-nava-chapter-meta]'),mv=clean(meta&&meta.getAttribute('data-volume-title'),400);if(mv)return mv;var tags=[].slice.call(root.querySelectorAll('a[rel="tag"]')).map(function(a){return clean(a.textContent,300)}).filter(function(x){return /(?:cilt|volume|vol\.?)\s*\d/i.test(x)});if(tags[0])return tags[0];var h=pageTitle(root),m=h.match(/^(.+?\b(?:cilt|volume|vol\.?)\s*\d+(?:\.\d+)?)/i);return m?clean(m[1],400):''}
  function isVolume(){return !!((d.body&&d.body.classList.contains('nava-app-volume'))||(!isReader()&&volumeTitle(d)))}
  function isSeries(){return !!(d.body&&d.body.classList.contains('nava-app-series'))}
  function relevant(){return isReader()||isVolume()||isSeries()}
  function stripVolume(v){return clean(v,400).replace(/\s+(?:cilt|volume|vol\.?)\s*\d+(?:\.\d+)?(?:\s.*)?$/i,'').trim()}
  function volumeNo(v){var m=clean(v,600).match(/(?:cilt|volume|vol\.?)\s*([0-9]+(?:\.[0-9]+)?)/i);return m?m[1]:''}
  function seriesTitle(root){root=root||d;if(isSeries()&&root===d)return pageTitle(root);var vt=volumeTitle(root);if(vt){var s=stripVolume(vt);if(s)return s}var h=pageTitle(root),s2=stripVolume(h);if(s2&&s2!==h)return s2;return''}
  function groupTitle(root,fallback){root=root||d;var vt=volumeTitle(root);if(vt)return vt;var s=seriesTitle(root)||seriesTitle(d),n=volumeNo(fallback||pageTitle(root));return n?(s?s+' Cilt '+n:'Cilt '+n):(s||clean(fallback,300)||'İçerik')}
  function state(){try{var x=JSON.parse(call('listDownloads')||'{}');if(!Array.isArray(x.items))x.items=[];return x}catch(_){return{items:[]}}}
  function downloadedSet(){var o=Object.create(null);state().items.forEach(function(x){var u=canonical(x&&x.url);if(u)o[u]=1});return o}

  function cleanupLegacy(){
    ['nava-download-menu-v12141','nava-download-menu-v12138','nava-offline-library-btn-v12131','nava-offline-reader-download-v12131','nava-offline-volume-btn-v12131'].forEach(function(id){var x=d.getElementById(id);if(x)try{x.remove()}catch(_){}});
    [].slice.call(d.querySelectorAll('[data-nava-download-inline],.nava-app-download-card,.nava-download-inline')).forEach(function(x){try{x.remove()}catch(_){}});
    d.documentElement.classList.remove('nava-download-menu-open-v12141','nava-download-menu-open-v12138');
  }

  function launcher(){var b=d.getElementById('nava-download-launcher-v12142');if(!relevant()){if(b)b.remove();return null}if(b)return b;b=el('button','nava-download-launcher-v12142');b.id='nava-download-launcher-v12142';b.type='button';b.setAttribute('aria-label','İndirme');b.setAttribute('title','İndirme');b.innerHTML=ICON.download;b.onclick=show;d.body.append(b);return b}
  function sheet(){var wrap=d.getElementById('nava-download-menu-v12142');if(wrap)return wrap;wrap=el('div','nava-download-backdrop-v12142');wrap.id='nava-download-menu-v12142';wrap.hidden=true;var p=el('section','nava-download-sheet-v12142'),head=el('header','nava-download-head-v12142'),copy=el('div'),close=el('button','nava-download-close-v12142','×');copy.append(el('strong','','İndirme'),el('span','nava-download-sub-v12142',''));close.type='button';close.setAttribute('aria-label','Kapat');close.onclick=hide;head.append(copy,close);var actions=el('div','nava-download-actions-v12142');actions.dataset.actions='1';var status=el('div','nava-download-status-v12142');status.dataset.status='1';p.append(head,actions,status);wrap.append(p);wrap.onclick=function(e){if(e.target===wrap)hide()};d.body.append(wrap);return wrap}
  function hide(){var x=d.getElementById('nava-download-menu-v12142');if(x)x.hidden=true}
  function setStatus(t,error){var x=sheet().querySelector('[data-status]');x.textContent=t||'';x.className='nava-download-status-v12142'+(error?' is-error':'')}
  function row(icon,title,sub,fn,primary){var b=el('button','nava-download-row-v12142'+(primary?' is-primary':''));b.type='button';b.disabled=busy;var ic=el('span','nava-download-row-icon-v12142');ic.innerHTML=icon;var cp=el('span','nava-download-row-copy-v12142');cp.append(el('strong','',title),el('small','',sub||''));b.append(ic,cp,el('span','nava-download-row-chevron-v12142','›'));b.onclick=fn;return b}

  function chapterItemsFrom(root,base,group){var seen=Object.create(null),out=[];[].slice.call(root.querySelectorAll('#clwd a[href],#chapters a[href],[data-nava-chapter-list] a[href],.eplister a[href]')).forEach(function(a){try{var u=canonical(new URL(a.getAttribute('href'),base).href);if(!u||seen[u])return;var text=clean(a.textContent,220),box=clean((a.closest('li,article,div')||a).textContent,320),joined=text+' '+box;if(!/(?:bölüm|bolum|chapter|episode|ep\.?)\s*\d/i.test(joined))return;seen[u]=1;out.push({url:u,title:text||box||'Bölüm',seriesTitle:group||'İçerik',kind:'chapter'})}catch(_){}});return out}
  function volumeLinks(){var seen=Object.create(null),out=[],series=seriesTitle(d);[].slice.call(d.querySelectorAll('a[href]')).forEach(function(a){try{var text=clean(a.textContent,220),box=clean((a.closest('li,article,.bs,.bsx,.eplister,.listupd,div')||a).textContent,340),joined=text+' '+box;if(!/(?:cilt|volume|vol\.?)\s*\d+/i.test(joined))return;var u=canonical(a.href);if(!u||seen[u]||u===currentUrl())return;seen[u]=1;var title=text||box||'Cilt';var n=volumeNo(joined);out.push({url:u,title:title,groupTitle:n?(series?series+' Cilt '+n:'Cilt '+n):title})}catch(_){}});return out.slice(0,100)}
  function downloadCurrent(){var group=groupTitle(d,pageTitle(d));call('download',currentUrl(),pageTitle(d),group,isReader()?'chapter':(isVolume()?'volume':'page'));setStatus('İndirme başladı.');}
  function downloadVolume(){var group=groupTitle(d,pageTitle(d)),items=[{url:currentUrl(),title:pageTitle(d),seriesTitle:group,kind:'volume'}].concat(chapterItemsFrom(d,location.href,group)),done=downloadedSet();items=items.filter(function(x){return !done[canonical(x.url)]});if(!items.length){setStatus('Bu cilt zaten indirilmiş.');return}call('downloadBatch',JSON.stringify(items));setStatus(items.length+' içerik indirme sırasına alındı.');}
  async function fetchVolume(v){var r=await fetch(v.url,{credentials:'include',cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);var html=await r.text(),doc=new DOMParser().parseFromString(html,'text/html'),group=volumeTitle(doc)||v.groupTitle||groupTitle(doc,v.title);return[{url:v.url,title:v.title,seriesTitle:group,kind:'volume'}].concat(chapterItemsFrom(doc,v.url,group))}
  async function downloadAll(){if(busy)return;var vols=volumeLinks();if(!vols.length){setStatus('Cilt bağlantısı bulunamadı.',true);return}busy=true;render();var all=[],seen=downloadedSet();try{for(var i=0;i<vols.length;i++){setStatus('Ciltler taranıyor '+(i+1)+'/'+vols.length);try{(await fetchVolume(vols[i])).forEach(function(x){var u=canonical(x.url);if(u&&!seen[u]){seen[u]=1;all.push(x)}})}catch(_){}}if(!all.length){setStatus('İndirilecek yeni içerik yok.');return}call('downloadBatch',JSON.stringify(all.slice(0,700)));setStatus(Math.min(all.length,700)+' içerik indirme sırasına alındı.')}finally{busy=false;render()}}
  function openLibrary(){hide();if(typeof w.navaOpenDownloads==='function'){w.navaOpenDownloads();return}setTimeout(function(){if(typeof w.navaOpenDownloads==='function')w.navaOpenDownloads()},120)}

  function render(){var s=sheet(),a=s.querySelector('[data-actions]'),sub=s.querySelector('.nava-download-sub-v12142');a.replaceChildren();sub.textContent=pageTitle(d);if(isReader())a.append(row(ICON.download,'Bu bölümü indir','Çevrimdışı okumak için kaydet',downloadCurrent,true));else if(isVolume())a.append(row(ICON.book,'Bu cildi indir','Cilt sayfası ve bölümleri kaydet',downloadVolume,true));else if(isSeries())a.append(row(ICON.stack,'Tüm ciltleri indir','Eserdeki ciltleri sıraya al',downloadAll,true));a.append(row(ICON.folder,'İndirilenler','Kaydettiğin içerikleri aç',openLibrary,false))}
  function show(){cleanupLegacy();launcher();render();sheet().hidden=false;setStatus('')}
  function sync(){cleanupLegacy();launcher()}

  w.navaOfflineNativeEvent=function(ev){try{if(typeof prevNative==='function')prevNative(ev)}catch(_){}ev=ev||{};var t=String(ev.type||'');if(t==='start')setStatus('İndiriliyor: '+clean(ev.title,80));else if(t==='complete')setStatus('İndirildi: '+clean(ev.title,80));else if(t==='batch-complete')setStatus('İndirme tamamlandı: '+Number(ev.ok||0)+' başarılı'+(Number(ev.failed||0)?' • '+Number(ev.failed)+' hata':''),Number(ev.failed||0)>0);else if(t==='error')setStatus(clean(ev.message,220)||'İndirme başarısız.',true)};
  function init(){cleanupLegacy();sheet();sync();if(!observer&&d.body){observer=new MutationObserver(function(){sync()});observer.observe(d.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class']})}w.addEventListener('pageshow',function(){setTimeout(sync,80);setTimeout(sync,500)},{passive:true});d.addEventListener('visibilitychange',function(){if(!d.hidden)setTimeout(sync,80)})}
  if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(document,window);
