/* Nava Android 12.1.49 — series-page download picker + download center/queue, based on 12.1.47. */
;(function(d,w){
'use strict';
if(w.__navaDownloadV12149)return;w.__navaDownloadV12149=true;
if(!w.__NAVA_ANDROID_APP__||!w.NavaOffline)return;
var ICON='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v11"/><path d="m7.5 10 4.5 4.5 4.5-4.5"/><path d="M5 20h14"/></svg>',busy=false,observer=null,queue=[],queueState={done:0,total:0,active:false};
function clean(v,n){return String(v==null?'':v).replace(/\s+/g,' ').trim().slice(0,n||500)}
function el(t,c,x){var e=d.createElement(t);if(c)e.className=c;if(x!=null)e.textContent=x;return e}
function call(m){try{var f=w.NavaOffline&&w.NavaOffline[m];if(typeof f!=='function')return null;return f.apply(w.NavaOffline,[].slice.call(arguments,1))}catch(_){return null}}
function canon(v){try{var u=new URL(String(v||''),location.href),h=(u.hostname||'').toLowerCase();if(h!=='verudanava.com'&&h!=='www.verudanava.com'&&h!=='verudanava.blogspot.com')return'';u.hash='';u.protocol='https:';u.hostname='www.verudanava.com';u.port='';return u.href}catch(_){return''}}
function isSeries(){return!!(d.body&&d.body.classList.contains('nava-app-series'))}
function pageTitle(r){r=r||d;var x=r.querySelector('header h1[itemprop="name"],main h1,.nava-series-title-v2,h1');return clean(x?x.textContent:(r===d?d.title:''),300)||'Eser'}
function stripVolume(v){return clean(v,400).replace(/\s+(?:cilt|volume|vol\.?)\s*\d+(?:\.\d+)?(?:\s.*)?$/i,'').trim()}
function volumeNo(v){var m=clean(v,600).match(/(?:cilt|volume|vol\.?)\s*([0-9]+(?:\.[0-9]+)?)/i);return m?m[1]:''}
function seriesTitle(){return pageTitle(d)}
function downloadedSet(){var out=Object.create(null);try{var x=JSON.parse(call('listDownloads')||'{}');(x.items||[]).forEach(function(i){var u=canon(i&&i.url);if(u)out[u]=1})}catch(_){}return out}
function volumeLinks(){var seen=Object.create(null),out=[],series=seriesTitle();[].slice.call(d.querySelectorAll('a[href]')).forEach(function(a){try{var t=clean(a.textContent,220),box=clean((a.closest('li,article,.bs,.bsx,.eplister,.listupd,div')||a).textContent,360),mix=t+' '+box;if(!/(?:cilt|volume|vol\.?)\s*\d+/i.test(mix))return;var u=canon(a.href);if(!u||seen[u]||u===canon(location.href))return;seen[u]=1;var n=volumeNo(mix),name=n?'Cilt '+n:(t||'Cilt');out.push({url:u,title:name,seriesTitle:series,n:n||'9999'})}catch(_){}});out.sort(function(a,b){return(Number(a.n)||9999)-(Number(b.n)||9999)});return out.slice(0,100)}
function chapterItemsFrom(doc,base,group){var seen=Object.create(null),out=[];[].slice.call(doc.querySelectorAll('#clwd a[href],#chapters a[href],[data-nava-chapter-list] a[href],.eplister a[href]')).forEach(function(a){try{var u=canon(new URL(a.getAttribute('href'),base).href);if(!u||seen[u])return;var t=clean(a.textContent,220),box=clean((a.closest('li,article,div')||a).textContent,340),mix=t+' '+box;if(!/(?:bölüm|bolum|chapter|episode|ep\.?|ch\.?)\s*\d/i.test(mix))return;seen[u]=1;out.push({url:u,title:t||box||'Bölüm',seriesTitle:group,kind:'chapter'})}catch(_){}});return out}
async function fetchVolume(v){var r=await fetch(v.url,{credentials:'include',cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);var h=await r.text(),doc=new DOMParser().parseFromString(h,'text/html'),group=v.seriesTitle+' '+v.title;return[{url:v.url,title:v.title,seriesTitle:group,kind:'volume'}].concat(chapterItemsFrom(doc,v.url,group))}
function removeOldSeriesDownload(){[].slice.call(d.querySelectorAll('main button,main a,#nava-app-page button,#nava-app-page a')).forEach(function(x){if(x.id==='nava-series-download-v12149'||x.closest('#nava-download-center-v12149,#nava-series-download-picker-v12149'))return;var t=clean(x.textContent,100);if(/^(?:Eseri indir|Tüm ciltleri indir)$/i.test(t))try{x.remove()}catch(_){}})}
function summaryAnchor(){var all=[].slice.call(d.querySelectorAll('button,a'));for(var i=0;i<all.length;i++){var t=clean(all[i].textContent,100);if(/^Özeti\s+Oku$/i.test(t))return all[i]}return null}
function seriesButton(){var old=d.getElementById('nava-series-download-v12149');if(!isSeries()){if(old)old.remove();return null}if(old)return old;var anchor=summaryAnchor();if(!anchor)return null;var b=el('button','nava-series-download-v12149');b.id='nava-series-download-v12149';b.type='button';b.innerHTML=ICON+'<span>Eseri indir</span>';b.onclick=openPicker;var host=anchor.parentElement||anchor;host.insertBefore(b,anchor.nextSibling);return b}
function picker(){var q=d.getElementById('nava-series-download-picker-v12149');if(q)return q;q=el('div','nava-v12149-backdrop');q.id='nava-series-download-picker-v12149';q.hidden=true;q.innerHTML='<section class="nava-v12149-sheet"><header><div><strong>Ciltleri seç</strong><span data-picker-sub></span></div><button type="button" data-close aria-label="Kapat">×</button></header><div class="nava-v12149-picker-actions"><button type="button" data-all>Tümünü seç</button><button type="button" data-none>Temizle</button></div><div class="nava-v12149-volume-list" data-volume-list></div><footer><button type="button" class="is-primary" data-start>İndirme sırasına ekle</button></footer></section>';q.querySelector('[data-close]').onclick=function(){q.hidden=true};q.querySelector('[data-all]').onclick=function(){q.querySelectorAll('input[type=checkbox]').forEach(function(x){x.checked=true});syncPicker()};q.querySelector('[data-none]').onclick=function(){q.querySelectorAll('input[type=checkbox]').forEach(function(x){x.checked=false});syncPicker()};q.querySelector('[data-start]').onclick=startSelected;q.onclick=function(e){if(e.target===q)q.hidden=true};d.body.append(q);return q}
function openPicker(e){if(e){e.preventDefault();e.stopPropagation()}var vols=volumeLinks(),q=picker(),list=q.querySelector('[data-volume-list]');list.replaceChildren();vols.forEach(function(v,i){var row=el('label','nava-v12149-volume-row');row.innerHTML='<input type="checkbox" data-index="'+i+'" checked><span><strong>'+clean(v.title,120)+'</strong><small>Bu cilt ve bölümleri</small></span>';row.querySelector('input').onchange=syncPicker;list.append(row)});q._volumes=vols;q.querySelector('[data-picker-sub]').textContent=vols.length?seriesTitle():'İndirilebilir cilt bulunamadı';q.hidden=false;syncPicker()}
function syncPicker(){var q=picker(),n=q.querySelectorAll('input[type=checkbox]:checked').length,b=q.querySelector('[data-start]');b.disabled=!n||busy;b.textContent=n?(n+' cildi indirme sırasına ekle'):'Cilt seç'}
async function startSelected(){if(busy)return;var q=picker(),vols=q._volumes||[],chosen=[];q.querySelectorAll('input[type=checkbox]:checked').forEach(function(x){var v=vols[Number(x.dataset.index)];if(v)chosen.push(v)});if(!chosen.length)return;busy=true;syncPicker();var set=downloadedSet(),items=[];try{for(var i=0;i<chosen.length;i++){q.querySelector('[data-picker-sub]').textContent='Hazırlanıyor '+(i+1)+'/'+chosen.length;try{var got=await fetchVolume(chosen[i]);got.forEach(function(x){var u=canon(x.url);if(u&&!set[u]){set[u]=1;items.push(x)}})}catch(_){}}if(!items.length){q.querySelector('[data-picker-sub]').textContent='Seçilenler zaten indirilmiş.';return}queue=items.slice(0,900);queueState={done:0,total:queue.length,active:true};renderQueue();q.hidden=true;call('downloadBatch',JSON.stringify(queue));openCenter()}finally{busy=false;syncPicker()}}
function center(){var q=d.getElementById('nava-download-center-v12149');if(q)return q;q=el('div','nava-v12149-backdrop');q.id='nava-download-center-v12149';q.hidden=true;q.innerHTML='<section class="nava-v12149-sheet"><header><div><strong>İndirmeler</strong><span>İndirilenler ve indirme sırası</span></div><button type="button" data-close aria-label="Kapat">×</button></header><div class="nava-v12149-center-actions"><button type="button" data-library><strong>İndirilenler</strong><small>İndirdiğin eserleri yönet</small></button><button type="button" data-queue><strong>İndirme sırası</strong><small data-queue-summary>Sıra boş</small></button></div><div class="nava-v12149-queue" data-queue-list hidden></div></section>';q.querySelector('[data-close]').onclick=function(){q.hidden=true};q.querySelector('[data-library]').onclick=function(){q.hidden=true;if(typeof w.navaOpenDownloads==='function')w.navaOpenDownloads()};q.querySelector('[data-queue]').onclick=function(){var x=q.querySelector('[data-queue-list]');x.hidden=!x.hidden;renderQueue()};q.onclick=function(e){if(e.target===q)q.hidden=true};d.body.append(q);return q}
function renderQueue(){var q=center(),sum=q.querySelector('[data-queue-summary]'),list=q.querySelector('[data-queue-list]');sum.textContent=queueState.active?(queueState.done+'/'+queueState.total+' tamamlandı'):(queue.length?queue.length+' öğe':'Sıra boş');list.replaceChildren();if(!queue.length){list.append(el('div','nava-v12149-empty','İndirme sırasında öğe yok.'));return}queue.slice(0,120).forEach(function(i,idx){var row=el('div','nava-v12149-queue-row');row.innerHTML='<span>'+(idx<queueState.done?'✓':'↓')+'</span><div><strong>'+clean(i.title,160)+'</strong><small>'+clean(i.seriesTitle,180)+'</small></div>';list.append(row)})}
function openCenter(e){if(e){e.preventDefault();e.stopPropagation()}var q=center();renderQueue();q.hidden=false}
function hijackTopDownload(){var b=d.getElementById('nava-download-top-v12147');if(!b)return false;if(b.dataset.nava12149==='1')return true;b.dataset.nava12149='1';b.onclick=openCenter;b.setAttribute('title','İndirmeler');b.setAttribute('aria-label','İndirmeler');return true}
var prev=w.navaOfflineNativeEvent||null;w.navaOfflineNativeEvent=function(ev){try{if(typeof prev==='function')prev(ev)}catch(_){}ev=ev||{};var t=String(ev.type||'');if(t==='complete'&&queueState.active){queueState.done=Math.min(queueState.total,queueState.done+1);renderQueue()}else if(t==='batch-complete'){queueState.active=false;queueState.done=queueState.total;renderQueue()}else if(t==='error'){renderQueue()}};
function sync(){removeOldSeriesDownload();seriesButton();hijackTopDownload()}
function init(){center();picker();sync();if(d.body&&!observer){observer=new MutationObserver(function(){sync()});observer.observe(d.body,{childList:true,subtree:true})}w.addEventListener('pageshow',function(){setTimeout(sync,0);setTimeout(sync,400)},{passive:true})}
if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(document,window);