/* Nava Android 12.1.58 — grouped volume queue + notification clear + offline refresh. */
;(function(d,w){
'use strict';
if(w.__navaUxV12158)return;w.__navaUxV12158=true;
if(!w.__NAVA_ANDROID_APP__)return;
var QUEUE_KEY='nava_download_queue_v12149',STATE_KEY='nava_download_group_state_v12158';
function clean(v,n){return String(v==null?'':v).replace(/\s+/g,' ').trim().slice(0,n||500)}
function canon(v){try{var u=new URL(String(v||''),location.href);if(!/(^|\.)verudanava\.(?:com|blogspot\.com)$/i.test(u.hostname))return'';u.hash='';u.search='';u.protocol='https:';u.hostname='www.verudanava.com';u.port='';return u.href.replace(/\/$/,'')}catch(_){return''}}
function volNo(v){var m=clean(v,700).match(/(?:cilt|volume|vol\.?)\s*([0-9]+(?:\.[0-9]+)?)/i);return m?m[1]:''}
function stripVol(v){return clean(v,400).replace(/\s+(?:cilt|volume|vol\.?)\s*\d+(?:\.\d+)?(?:\s.*)?$/i,'').trim()}
function queue(){try{var q=JSON.parse(localStorage.getItem(QUEUE_KEY)||'[]');return Array.isArray(q)?q:[]}catch(_){return[]}}
function state(){try{var s=JSON.parse(localStorage.getItem(STATE_KEY)||'{}');return s&&typeof s==='object'?s:{}}catch(_){return{}}}
function saveState(s){try{localStorage.setItem(STATE_KEY,JSON.stringify(s))}catch(_){}}
function info(x){x=x||{};var st=clean(x.seriesTitle,350),title=clean(x.title,220),n=volNo(st+' '+title),series=stripVol(st)||stripVol(title)||'İçerik';return{key:series+'|'+(n||'0'),series:series,volume:n?('Cilt '+n):'İçerik',isChapter:String(x.kind||'').toLowerCase()==='chapter'}}
function ensureFromQueue(s,q){var urlSeen={};(q||[]).forEach(function(x){var u=canon(x&&x.url);if(!u||urlSeen[u])return;urlSeen[u]=1;var g=info(x),z=s[g.key]||(s[g.key]={series:g.series,volume:g.volume,items:{},updated:Date.now()});z.series=g.series;z.volume=g.volume;z.updated=Date.now();if(!z.items[u])z.items[u]={status:clean(x.status,30)||'waiting',done:Number(x.done)||0,total:Number(x.total)||0,isChapter:g.isChapter};else{z.items[u].status=clean(x.status,30)||z.items[u].status;z.items[u].done=Number(x.done)||z.items[u].done||0;z.items[u].total=Number(x.total)||z.items[u].total||0;z.items[u].isChapter=g.isChapter}});return s}
function findGroupByUrl(s,u){var ks=Object.keys(s||{});for(var i=0;i<ks.length;i++){var z=s[ks[i]];if(z&&z.items&&z.items[u])return z}return null}
function updateEventBefore(ev){var s=ensureFromQueue(state(),queue()),u=canon(ev&&ev.url),t=String(ev&&ev.type||'');if(u){var g=findGroupByUrl(s,u);if(g){var it=g.items[u];if(t==='start'||t==='progress')it.status='active';else if(t==='complete')it.status='done';else if(t==='error')it.status='error';if(ev.done!=null)it.done=Number(ev.done)||0;if(ev.total!=null)it.total=Number(ev.total)||0;g.updated=Date.now()}}if(t==='batch-complete'){Object.keys(s).forEach(function(k){var g=s[k];Object.keys(g.items||{}).forEach(function(u2){if(g.items[u2].status!=='error')g.items[u2].status='done'});g.updated=Date.now()})}saveState(s)}
function pctOf(g){var items=Object.keys(g.items||{}).map(function(k){return g.items[k]}),total=items.length;if(!total)return 0;var p=0;items.forEach(function(x){if(x.status==='done')p+=1;else if(x.status==='active'&&x.total>0)p+=Math.max(0,Math.min(1,(Number(x.done)||0)/Number(x.total)))});return Math.max(0,Math.min(100,Math.round(p/total*100)))}
function renderGroups(){var hub=d.getElementById('nava-download-hub-v12149');if(!hub)return;var list=hub.querySelector('[data-queue-list]'),count=hub.querySelector('[data-queue-count]');if(!list)return;var s=ensureFromQueue(state(),queue());saveState(s);var groups=Object.keys(s).map(function(k){return s[k]}).filter(function(g){return g&&g.items&&Object.keys(g.items).length}).sort(function(a,b){return(Number(volNo(a.volume))||9999)-(Number(volNo(b.volume))||9999)});list.replaceChildren();if(count)count.textContent=groups.length?(groups.length+' cilt'):'';if(!groups.length){var e=d.createElement('div');e.className='nava-download-queue-empty-v12149';e.textContent='Sıra boş.';list.append(e);return}groups.slice(0,20).forEach(function(g){var items=Object.keys(g.items).map(function(k){return g.items[k]}),done=items.filter(function(x){return x.status==='done'}).length,err=items.filter(function(x){return x.status==='error'}).length,active=items.some(function(x){return x.status==='active'}),chapters=items.filter(function(x){return x.isChapter}).length,pct=pctOf(g),row=d.createElement('div'),head=d.createElement('div'),copy=d.createElement('span'),strong=d.createElement('strong'),small=d.createElement('small'),bar=d.createElement('div'),fill=d.createElement('i');row.className='nava-download-queue-group-v12158';head.className='nava-download-queue-group-head-v12158';strong.textContent=g.series+' • '+g.volume;var status=err?'Hata':active?'İndiriliyor':done===items.length?'Tamamlandı':'Sırada';small.textContent=status+' • '+chapters+' bölüm • '+pct+'%';copy.append(strong,small);head.append(copy);bar.className='nava-download-progress-v12158';fill.style.width=pct+'%';bar.append(fill);row.append(head,bar);list.append(row)});if(groups.length>20){var more=d.createElement('div');more.className='nava-download-queue-more-v12149';more.textContent='+'+(groups.length-20)+' cilt daha';list.append(more)}}
function clearCompletedState(){var s=state(),q=queue(),live={};q.forEach(function(x){var u=canon(x&&x.url);if(u)live[u]=1});Object.keys(s).forEach(function(k){var g=s[k],keep=false;Object.keys(g.items||{}).forEach(function(u){var it=g.items[u];if(live[u]||it.status==='error')keep=true});if(!keep)delete s[k]});saveState(s);renderGroups()}
var prevNative=w.navaOfflineNativeEvent;
w.navaOfflineNativeEvent=function(ev){updateEventBefore(ev||{});try{if(typeof prevNative==='function')prevNative(ev)}catch(e){console.error('Nava 12.1.58 native chain',e)}setTimeout(renderGroups,0);if(ev&&ev.type==='batch-complete')setTimeout(clearCompletedState,1400)};
function ensureOfflineRefresh(){var box=d.getElementById('nava-offline-browser-v12149');if(!box)return;var head=box.querySelector('.nava-offline-browser-head-v12147');if(!head||head.querySelector('.nava-offline-refresh-v12158'))return;var b=d.createElement('button');b.type='button';b.className='nava-offline-refresh-v12158';b.setAttribute('aria-label','İndirilenleri yenile');b.setAttribute('title','Yenile');b.textContent='↻';b.onclick=function(e){e.preventDefault();e.stopPropagation();b.classList.add('is-refreshing');try{if(typeof w.navaOpenDownloads==='function')w.navaOpenDownloads()}finally{setTimeout(function(){b.classList.remove('is-refreshing')},350)}};var settings=head.querySelector('.nava-offline-settings-btn-v12147');head.insertBefore(b,settings||null)}
async function clearNotifications(btn){var db=w.db,auth=w.auth,u=auth&&auth.currentUser;if(!db||!u)throw new Error('Oturum yok');var c=db.collection('users').doc(u.uid).collection('notifications'),removed=0;for(var i=0;i<30;i++){var snap=await c.limit(400).get();if(snap.empty)break;var batch=db.batch();snap.docs.forEach(function(x){batch.delete(x.ref)});await batch.commit();removed+=snap.size;if(snap.size<400)break}return removed}
function ensureNotificationClear(){var panel=d.getElementById('nava-notification-panel'),list=d.getElementById('nava-notification-list');if(!panel||!list)return;var actions=panel.querySelector('.nava-notification-head-actions');if(!actions){actions=d.createElement('div');actions.className='nava-notification-head-actions nava-notification-head-actions-v12158';var head=panel.querySelector('.nava-notification-head,header')||panel;head.append(actions)}var old=d.getElementById('nava-notification-clear-all-v12149');if(old){old.style.display='flex';old.hidden=false;if(old.parentNode!==actions)actions.append(old);return}var btn=d.getElementById('nava-notification-clear-all-v12158');if(btn)return;btn=d.createElement('button');btn.type='button';btn.id='nava-notification-clear-all-v12158';btn.className='nava-notification-head-button';btn.textContent='Tümünü temizle';btn.onclick=function(e){e.preventDefault();e.stopPropagation();if(btn.disabled)return;btn.disabled=true;btn.textContent='Temizleniyor…';clearNotifications(btn).then(function(n){btn.textContent=n?'Temizlendi':'Bildirim yok'}).catch(function(){btn.textContent='Tekrar dene'}).finally(function(){setTimeout(function(){btn.disabled=false;btn.textContent='Tümünü temizle'},1000)})};actions.append(btn)}
function afterUiClick(e){var t=e.target&&e.target.closest?e.target.closest('#nava-download-top-v12149,[data-open-library],#nava-app-bell,[data-nava-notifications-open]'):null;if(!t)return;setTimeout(function(){renderGroups();ensureOfflineRefresh();ensureNotificationClear()},0);setTimeout(function(){ensureOfflineRefresh();ensureNotificationClear()},180)}
d.addEventListener('click',afterUiClick,true);
function init(){ensureOfflineRefresh();ensureNotificationClear();renderGroups();setTimeout(function(){ensureOfflineRefresh();ensureNotificationClear();renderGroups()},500);setTimeout(function(){ensureNotificationClear()},1800)}
if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',init,{once:true});else init();
w.addEventListener('pageshow',function(){setTimeout(init,0)},{passive:true});
})(document,window);
