/* Nava Android 12.1.48 — isolated download control, topbar untouched. */
;(function(d,w){
'use strict';
if(w.__navaDownloadV12148)return;w.__navaDownloadV12148=true;
if(!w.__NAVA_ANDROID_APP__||!w.NavaOffline)return;
var ICON='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v11"/><path d="m7.5 10 4.5 4.5 4.5-4.5"/><path d="M5 20h14"/></svg>',FOLDER='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M3 7h7l2 2h9v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z"/></svg>',busy=false,observer=null,prevNative=w.navaOfflineNativeEvent||null;
function clean(v,n){return String(v==null?'':v).replace(/\s+/g,' ').trim().slice(0,n||500)}
function el(t,c,x){var e=d.createElement(t);if(c)e.className=c;if(x!=null)e.textContent=x;return e}
function call(m){try{var n=w.NavaOffline;if(!n||typeof n[m]!=='function')return null;return n[m].apply(n,[].slice.call(arguments,1))}catch(_){return null}}
function canon(v){try{var u=new URL(String(v||''),location.href),h=(u.hostname||'').toLowerCase();if(h!=='verudanava.com'&&h!=='www.verudanava.com'&&h!=='verudanava.blogspot.com')return'';u.hash='';u.protocol='https:';u.hostname='www.verudanava.com';u.port='';return u.href}catch(_){return''}}
function isReader(){return!!((d.body&&d.body.classList.contains('nava-app-reader'))||d.querySelector('[data-nava-chapter-meta],#reader,.nava-reader-title-v2'))}
function pageTitle(r){r=r||d;var x=r.querySelector('.nava-reader-title-v2,header h1[itemprop="name"],main h1,h1');return clean(x?x.textContent:(r===d?d.title:''),300)||'İçerik'}
function volumeTitle(r){r=r||d;var m=r.querySelector('[data-nava-chapter-meta]'),v=clean(m&&m.getAttribute('data-volume-title'),400);if(v)return v;var tags=[].slice.call(r.querySelectorAll('a[rel="tag"]')).map(function(a){return clean(a.textContent,300)}).filter(function(x){return/(?:cilt|volume|vol\.?)\s*\d/i.test(x)});if(tags[0])return tags[0];var h=pageTitle(r),z=h.match(/^(.+?\b(?:cilt|volume|vol\.?)\s*\d+(?:\.\d+)?)/i);return z?clean(z[1],400):''}
function isVolume(){return!!((d.body&&d.body.classList.contains('nava-app-volume'))||(!isReader()&&volumeTitle(d)))}
function isSeries(){return!!(d.body&&d.body.classList.contains('nava-app-series'))}
function relevant(){return isReader()||isVolume()||isSeries()}
function currentUrl(){return canon(location.href)||location.href}
function stripVolume(v){return clean(v,400).replace(/\s+(?:cilt|volume|vol\.?)\s*\d+(?:\.\d+)?(?:\s.*)?$/i,'').trim()}
function volumeNo(v){var m=clean(v,600).match(/(?:cilt|volume|vol\.?)\s*([0-9]+(?:\.[0-9]+)?)/i);return m?m[1]:''}
function seriesTitle(r){r=r||d;if(isSeries()&&r===d)return pageTitle(r);var vt=volumeTitle(r);if(vt){var s=stripVolume(vt);if(s)return s}var h=pageTitle(r),x=stripVolume(h);if(x&&x!==h)return x;return''}
function groupTitle(r,f){r=r||d;var vt=volumeTitle(r);if(vt)return vt;var s=seriesTitle(r)||seriesTitle(d),n=volumeNo(f||pageTitle(r));return n?(s?s+' Cilt '+n:'Cilt '+n):(s||clean(f,300)||'İçerik')}
function downloadedSet(){var o=Object.create(null);try{var x=JSON.parse(call('listDownloads')||'{}');(x.items||[]).forEach(function(i){var u=canon(i&&i.url);if(u)o[u]=1})}catch(_){}return o}
function chapterItemsFrom(r,b,g){var seen=Object.create(null),out=[];[].slice.call(r.querySelectorAll('#clwd a[href],#chapters a[href],[data-nava-chapter-list] a[href],.eplister a[href]')).forEach(function(a){try{var u=canon(new URL(a.getAttribute('href'),b).href);if(!u||seen[u])return;var t=clean(a.textContent,220),box=clean((a.closest('li,article,div')||a).textContent,320);if(!/(?:bölüm|bolum|chapter|episode|ep\.?|ch\.?)\s*\d/i.test(t+' '+box))return;seen[u]=1;out.push({url:u,title:t||box||'Bölüm',seriesTitle:g||'İçerik',kind:'chapter'})}catch(_){}});return out}
function volumeLinks(){var seen=Object.create(null),out=[],series=seriesTitle(d);[].slice.call(d.querySelectorAll('a[href]')).forEach(function(a){try{var t=clean(a.textContent,220),box=clean((a.closest('li,article,.bs,.bsx,.eplister,.listupd,div')||a).textContent,340),j=t+' '+box;if(!/(?:cilt|volume|vol\.?)\s*\d+/i.test(j))return;var u=canon(a.href);if(!u||seen[u]||u===currentUrl())return;seen[u]=1;var title=t||box||'Cilt',n=volumeNo(j);out.push({url:u,title:title,groupTitle:n?(series?series+' Cilt '+n:'Cilt '+n):title})}catch(_){}});return out.slice(0,100)}
async function fetchVolume(v){var r=await fetch(v.url,{credentials:'include',cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);var h=await r.text(),doc=new DOMParser().parseFromString(h,'text/html'),g=volumeTitle(doc)||v.groupTitle||groupTitle(doc,v.title);return[{url:canon(v.url),title:v.title,seriesTitle:g,kind:'volume'}].concat(chapterItemsFrom(doc,v.url,g))}
function cleanup(){['nava-download-top-v12147','nava-download-pop-v12147','nava-download-launcher-v12142','nava-download-launcher-v12143','nava-download-launcher-v12145','nava-download-launcher-v12146','nava-download-menu-v12138','nava-download-menu-v12139','nava-download-menu-v12141','nava-download-menu-v12142','nava-download-menu-v12143','nava-download-menu-v12145','nava-download-hub-v12146','nava-download-center-v12143','nava-offline-library-btn-v12131','nava-offline-reader-download-v12131','nava-offline-volume-btn-v12131'].forEach(function(id){var x=d.getElementById(id);if(x)try{x.remove()}catch(_){}});[].slice.call(d.querySelectorAll('[data-nava-download-inline],.nava-app-download-card,.nava-download-inline')).forEach(function(x){try{x.remove()}catch(_){}})}
function launcher(){var b=d.getElementById('nava-download-launcher-v12148');if(!relevant()){if(b)b.remove();return null}if(b)return b;b=el('button','nava-download-launcher-v12148');b.id='nava-download-launcher-v12148';b.type='button';b.setAttribute('aria-label','İndirme');b.setAttribute('title','İndirme');b.innerHTML=ICON;b.onclick=show;d.body.append(b);return b}
function panel(){var q=d.getElementById('nava-download-panel-v12148');if(q)return q;q=el('div','nava-download-backdrop-v12148');q.id='nava-download-panel-v12148';q.hidden=true;var p=el('section','nava-download-sheet-v12148'),h=el('header','nava-download-head-v12148'),c=el('div'),x=el('button','nava-download-close-v12148','×');c.append(el('strong','','İndirme'),el('span','nava-download-context-v12148',''));x.type='button';x.setAttribute('aria-label','Kapat');x.onclick=hide;h.append(c,x);var a=el('div','nava-download-actions-v12148');a.dataset.actions='1';var s=el('div','nava-download-status-v12148');s.dataset.status='1';p.append(h,a,s);q.append(p);q.onclick=function(e){if(e.target===q)hide()};d.body.append(q);return q}
function hide(){var x=d.getElementById('nava-download-panel-v12148');if(x)x.hidden=true}
function status(t,e){var x=panel().querySelector('[data-status]');x.textContent=t||'';x.className='nava-download-status-v12148'+(e?' is-error':'')}
function action(ic,t,sub,fn,primary){var b=el('button','nava-download-row-v12148'+(primary?' is-primary':''));b.type='button';b.disabled=busy;var i=el('span','nava-download-row-icon-v12148');i.innerHTML=ic;var c=el('span','nava-download-row-copy-v12148');c.append(el('strong','',t),el('small','',sub||''));b.append(i,c,el('span','nava-download-row-arrow-v12148','›'));b.onclick=fn;return b}
function openLibrary(){hide();if(typeof w.navaOpenDownloads==='function')w.navaOpenDownloads();else status('İndirilenler açılamadı.',true)}
function downloadCurrent(){var g=groupTitle(d,pageTitle());call('download',currentUrl(),pageTitle(),g,isReader()?'chapter':(isVolume()?'volume':'page'));status('İndirme başladı.')}
function downloadVolume(){var g=groupTitle(d,pageTitle()),items=[{url:currentUrl(),title:pageTitle(),seriesTitle:g,kind:'volume'}].concat(chapterItemsFrom(d,location.href,g)),set=downloadedSet();items=items.filter(function(x){return!set[canon(x.url)]});if(!items.length){status('Bu cilt zaten indirilmiş.');return}call('downloadBatch',JSON.stringify(items));status(items.length+' içerik indiriliyor.')}
async function downloadSeries(){if(busy)return;var vols=volumeLinks();if(!vols.length){status('Cilt bulunamadı.',true);return}busy=true;render();var all=[],seen=downloadedSet();try{for(var i=0;i<vols.length;i++){status('Hazırlanıyor '+(i+1)+'/'+vols.length);try{(await fetchVolume(vols[i])).forEach(function(x){var u=canon(x.url);if(u&&!seen[u]){seen[u]=1;all.push(x)}})}catch(_){}}if(!all.length){status('Yeni indirilecek içerik yok.');return}all=all.slice(0,700);call('downloadBatch',JSON.stringify(all));status(all.length+' içerik indiriliyor.')}finally{busy=false;render()}}
function render(){var p=panel(),a=p.querySelector('[data-actions]'),ctx=p.querySelector('.nava-download-context-v12148');a.replaceChildren();ctx.textContent=pageTitle();if(isReader())a.append(action(ICON,'Bölümü indir','Bu bölümü çevrimdışı kaydet',downloadCurrent,true));else if(isVolume())a.append(action(ICON,'Cildi indir','Cilt ve içindeki bölümler',downloadVolume,true));else if(isSeries())a.append(action(ICON,'Eseri indir','Tüm cilt ve bölümler',downloadSeries,true));a.append(action(FOLDER,'İndirilenler','Kaydettiğin içerikleri aç',openLibrary,false))}
function show(e){if(e){e.preventDefault();e.stopPropagation()}cleanup();launcher();render();status('');panel().hidden=false}
function sync(){cleanup();launcher()}
w.navaOfflineNativeEvent=function(ev){try{if(typeof prevNative==='function')prevNative(ev)}catch(_){}ev=ev||{};var t=String(ev.type||'');if(t==='complete')status('İndirildi.');else if(t==='batch-complete')status('İndirme tamamlandı.');else if(t==='error')status(clean(ev.message,180)||'İndirme başarısız.',true)};
function init(){cleanup();panel();sync();if(d.body&&!observer){observer=new MutationObserver(function(){sync()});observer.observe(d.body,{childList:true,subtree:true})}w.addEventListener('pageshow',function(){setTimeout(sync,0);setTimeout(sync,400)},{passive:true});d.addEventListener('visibilitychange',function(){if(!d.hidden)setTimeout(sync,50)})}
if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(document,window);