/* Nava Android 12.1.43 — compact download center + stable topbar. */
;(function(d,w){
  'use strict';
  if(w.__navaDownloadMenuV12143)return;
  w.__navaDownloadMenuV12143=true;
  if(!w.__NAVA_ANDROID_APP__||!w.NavaOffline)return;

  var ICON='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v11"/><path d="m7.5 10 4.5 4.5 4.5-4.5"/><path d="M5 20h14"/></svg>';
  var busy=false,observer=null;
  function clean(v,n){return String(v==null?'':v).replace(/\s+/g,' ').trim().slice(0,n||400)}
  function el(tag,cls,text){var x=d.createElement(tag);if(cls)x.className=cls;if(text!=null)x.textContent=text;return x}
  function canon(value){try{var u=new URL(String(value||''),location.href);u.hash='';u.protocol='https:';u.hostname='www.verudanava.com';u.port='';return u.href}catch(_){return''}}
  function pageTitle(root){root=root||d;var x=root.querySelector('.nava-reader-title-v2,header h1[itemprop="name"],main h1,h1');return clean(x?x.textContent:(root===d?d.title:''),300)||'İçerik'}
  function isReader(){return !!(d.body&&d.body.classList.contains('nava-app-reader'))||!!d.querySelector('[data-nava-chapter-meta]')}
  function volumeTitle(root){root=root||d;var m=root.querySelector('[data-nava-chapter-meta]'),v=clean(m&&m.getAttribute('data-volume-title'),400);if(v)return v;var tags=[].slice.call(root.querySelectorAll('a[rel="tag"]')).map(function(a){return clean(a.textContent,300)}).filter(function(x){return /(?:cilt|volume|vol\.?)\s*\d/i.test(x)});if(tags[0])return tags[0];var h=pageTitle(root);return /(?:cilt|volume|vol\.?)\s*\d/i.test(h)?h:''}
  function isVolume(){return !!(d.body&&d.body.classList.contains('nava-app-volume'))||(!isReader()&&!!volumeTitle(d))}
  function isSeries(){return !!(d.body&&d.body.classList.contains('nava-app-series'))||(!isReader()&&!isVolume()&&!!d.querySelector('#chapters,#clwd,[data-nava-chapter-list],.eplister,.listupd'))}
  function stripVolume(v){return clean(v,400).replace(/\s+(?:cilt|volume|vol\.?)\s*\d+(?:\.\d+)?(?:\s.*)?$/i,'').trim()}
  function volumeNo(v){var m=clean(v,600).match(/(?:cilt|volume|vol\.?)\s*([0-9]+(?:\.[0-9]+)?)/i);return m?m[1]:''}
  function seriesTitle(root){root=root||d;if(isSeries()&&root===d)return pageTitle(root);var vt=volumeTitle(root);if(vt){var s=stripVolume(vt);if(s)return s}var h=pageTitle(root),s2=stripVolume(h);return s2||h}
  function groupTitle(root,fallback){root=root||d;var vt=volumeTitle(root)||clean(fallback,300),n=volumeNo(vt),s=seriesTitle(root);return n?(stripVolume(s||'')?(stripVolume(s)+' Cilt '+n):vt):(vt||s||'İçerik')}
  function listState(){try{var x=JSON.parse(w.NavaOffline.listDownloads()||'{}');if(!Array.isArray(x.items))x.items=[];return x}catch(_){return{items:[],wifiOnly:true}}}
  function downloadedSet(){var out=Object.create(null);listState().items.forEach(function(x){var u=canon(x&&x.url);if(u)out[u]=1});return out}

  function chapterItemsFrom(root,base,group){var seen=Object.create(null),out=[];[].slice.call(root.querySelectorAll('#clwd a[href],#chapters a[href],[data-nava-chapter-list] a[href],.eplister a[href]')).forEach(function(a){try{var u=new URL(a.getAttribute('href'),base);u.hash='';if(!/^https?:$/.test(u.protocol)||u.hostname.indexOf('verudanava')<0)return;u.protocol='https:';u.hostname='www.verudanava.com';u.port='';var text=clean(a.textContent,220),box=clean((a.closest('li,article,div')||a).textContent,320);if(!/(bölüm|bolum|chapter|episode|ep\.?|ch\.?)\s*\d/i.test(text+' '+box))return;if(seen[u.href])return;seen[u.href]=1;out.push({url:u.href,title:text||box||'Bölüm',seriesTitle:group||'İçerik',kind:'chapter'})}catch(_){}});return out.slice(0,400)}
  function volumeLinks(){var seen=Object.create(null),out=[],series=seriesTitle(d);[].slice.call(d.querySelectorAll('a[href]')).forEach(function(a){try{var text=clean(a.textContent,220),box=clean((a.closest('li,article,div')||a).textContent,320),joined=text+' '+box;if(!/(?:cilt|volume|vol\.?)\s*\d+/i.test(joined))return;var u=new URL(a.href,location.href);u.hash='';if(!/^https?:$/.test(u.protocol)||u.hostname.indexOf('verudanava')<0)return;u.protocol='https:';u.hostname='www.verudanava.com';u.port='';if(seen[u.href]||u.href===canon(location.href))return;seen[u.href]=1;var n=volumeNo(joined);out.push({url:u.href,title:text||box||('Cilt '+(n||'')),groupTitle:n?(stripVolume(series)+' Cilt '+n):series})}catch(_){}});return out.slice(0,120)}

  function shell(){var wrap=d.getElementById('nava-download-center-v12143');if(wrap)return wrap;wrap=el('div','nava-dl-backdrop-v12143');wrap.id='nava-download-center-v12143';wrap.hidden=true;var panel=el('section','nava-dl-panel-v12143'),head=el('header','nava-dl-head-v12143'),title=el('strong','','İndirme'),close=el('button','nava-dl-close-v12143','×');close.type='button';close.setAttribute('aria-label','Kapat');close.onclick=hide;head.append(title,close);var actions=el('div','nava-dl-actions-v12143');actions.dataset.actions='1';var queue=el('section','nava-dl-queue-v12143');queue.innerHTML='<div class="nava-dl-section-title-v12143">İndirme sırası</div><div data-queue-list="1"></div>';var prefs=el('label','nava-dl-pref-v12143'),cb=d.createElement('input');cb.type='checkbox';cb.dataset.wifi='1';cb.onchange=function(){try{w.NavaOffline.setWifiOnly(cb.checked)}catch(_){};setStatus(cb.checked?'Wi‑Fi ile indirme açık.':'Mobil veriyle indirme açık.','ok')};prefs.append(cb,el('span','','Yalnız Wi‑Fi ile indir'));var status=el('div','nava-dl-status-v12143');status.dataset.status='1';panel.append(head,actions,queue,prefs,status);wrap.append(panel);wrap.addEventListener('click',function(e){if(e.target===wrap)hide()});d.body.append(wrap);return wrap}
  function hide(){var x=d.getElementById('nava-download-center-v12143');if(x)x.hidden=true;d.documentElement.classList.remove('nava-download-open-v12143')}
  function setStatus(text,tone){var x=shell().querySelector('[data-status]');x.textContent=text||'';x.className='nava-dl-status-v12143'+(tone?' is-'+tone:'')}
  function action(label,sub,fn){var b=el('button','nava-dl-row-v12143');b.type='button';if(busy)b.disabled=true;var copy=el('span','nava-dl-row-copy-v12143');copy.append(el('strong','',label),el('small','',sub||''));b.append(copy,el('span','nava-dl-row-arrow-v12143','›'));b.onclick=function(e){e.preventDefault();e.stopPropagation();fn()};return b}
  function queueData(){try{return typeof w.navaGetDownloadQueue==='function'?w.navaGetDownloadQueue():[]}catch(_){return[]}}
  function renderQueue(){var box=shell().querySelector('[data-queue-list]'),q=queueData();box.replaceChildren();if(!q.length){box.append(el('div','nava-dl-queue-empty-v12143','Sıra boş.'));return}q.slice(0,7).forEach(function(x){var row=el('div','nava-dl-queue-item-v12143'),copy=el('span'),status=x.status==='active'?(x.total?(Number(x.done||0)+'/'+Number(x.total||0)):'İndiriliyor'):x.status==='error'?'Hata':'Bekliyor';copy.append(el('strong','',clean(x.title,140)||'İçerik'),el('small','',status));row.append(copy);box.append(row)});if(q.length>7)box.append(el('div','nava-dl-queue-more-v12143','+'+(q.length-7)+' içerik daha'))}
  function render(){var p=shell(),actions=p.querySelector('[data-actions]'),idx=listState(),set=downloadedSet();p.querySelector('[data-wifi]').checked=idx.wifiOnly!==false;actions.replaceChildren();var url=canon(location.href),title=pageTitle(d),group=groupTitle(d,title);
    if(isReader())actions.append(action(set[url]?'Bölümü yeniden indir':'Bu bölümü indir',title,function(){if(typeof w.navaQueueSingleDownload==='function')w.navaQueueSingleDownload({url:url,title:title,seriesTitle:group,kind:'chapter'});setStatus('İndirme sırasına eklendi.','ok');renderQueue()}));
    else if(isVolume())actions.append(action('Bu cildi indir',chapterItemsFrom(d,location.href,group).length+' bölüm',function(){var items=[{url:url,title:title,seriesTitle:group,kind:'volume'}].concat(chapterItemsFrom(d,location.href,group)).filter(function(x){return !set[canon(x.url)]});if(!items.length){setStatus('Bu cilt zaten indirilmiş.','ok');return}if(typeof w.navaQueueDownloadBatch==='function')w.navaQueueDownloadBatch(items);setStatus(items.length+' içerik sıraya eklendi.','ok');renderQueue()}));
    else if(isSeries())actions.append(action('Tüm ciltleri indir',volumeLinks().length+' cilt',downloadAllVolumes));
    actions.append(action('İndirilenler',idx.items.length+' içerik',function(){hide();if(typeof w.navaOpenDownloads==='function')w.navaOpenDownloads()}));renderQueue()}
  function show(){render();var p=shell();p.hidden=false;d.documentElement.classList.add('nava-download-open-v12143');setStatus('','')}

  async function fetchVolume(v){var r=await fetch(v.url,{credentials:'include',cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);var html=await r.text(),doc=new DOMParser().parseFromString(html,'text/html'),group=volumeTitle(doc)||v.groupTitle||groupTitle(doc,v.title);return [{url:v.url,title:v.title,seriesTitle:group,kind:'volume'}].concat(chapterItemsFrom(doc,v.url,group))}
  async function downloadAllVolumes(){if(busy)return;var vols=volumeLinks();if(!vols.length){setStatus('Cilt bağlantısı bulunamadı.','error');return}busy=true;render();var all=[],seen=downloadedSet();setStatus('Ciltler hazırlanıyor…','ok');try{for(var i=0;i<vols.length;i++){setStatus('Ciltler hazırlanıyor '+(i+1)+'/'+vols.length,'ok');try{var got=await fetchVolume(vols[i]);got.forEach(function(x){var u=canon(x.url);if(u&&!seen[u]){seen[u]=1;all.push(x)}})}catch(_){}}if(!all.length){setStatus('İndirilecek yeni içerik yok.','ok');return}if(typeof w.navaQueueDownloadBatch==='function')w.navaQueueDownloadBatch(all.slice(0,800));setStatus(Math.min(all.length,800)+' içerik sıraya eklendi.','ok');renderQueue()}finally{busy=false;render()}}

  function removeLegacy(){['nava-download-menu-v12141','nava-offline-library-btn-v12131','nava-offline-volume-btn-v12131','nava-offline-reader-download-v12131'].forEach(function(id){var x=d.getElementById(id);if(x)try{x.remove()}catch(_){}})}
  function makeButton(){var b=el('button','nava-app-icon-btn nava-download-top-v12143');b.id='nava-download-btn-v12143';b.type='button';b.setAttribute('aria-label','İndirme');b.setAttribute('title','İndirme');b.innerHTML=ICON;b.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();show()},true);return b}
  function wire(){removeLegacy();var existing=d.getElementById('nava-download-btn-v12143'),host=isReader()?d.getElementById('nava-reader-top-v2'):d.getElementById('nava-app-topbar');if(!host){if(existing)existing.remove();return}if(existing&&existing.parentNode!==host)existing.remove();if(!d.getElementById('nava-download-btn-v12143')){var b=makeButton();if(isReader()){var more=host.querySelector('button[aria-label="Yazı"]');host.insertBefore(b,more||host.lastElementChild)}else host.appendChild(b)}}
  function init(){shell();wire();renderQueue();if(!observer&&d.body){var timer=0;observer=new MutationObserver(function(){clearTimeout(timer);timer=setTimeout(wire,40)});observer.observe(d.body,{childList:true,subtree:true})}w.addEventListener('pageshow',function(){setTimeout(wire,50);setTimeout(wire,450)},{passive:true});w.addEventListener('nava:offline-queue',function(){renderQueue();if(!shell().hidden)render()});d.addEventListener('visibilitychange',function(){if(!d.hidden)setTimeout(wire,50)})}
  if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',init,{once:true});else init();
  w.navaOpenDownloadCenter=show;
})(document,window);
