/* Nava Android 12.1.61 — visible v9 notification clear/delete controls. */
;(function(d,w){
'use strict';
if(w.__navaNotificationV12161)return;w.__navaNotificationV12161=true;
if(!w.__NAVA_ANDROID_APP__)return;
var db=null,auth=null,docs=[],unsub=null,authUnsub=null,observer=null,lastUid='';
function ready(){try{db=w.db||db||(w.firebase&&firebase.firestore&&firebase.firestore());auth=w.auth||auth||(w.firebase&&firebase.auth&&firebase.auth());return!!(db&&auth)}catch(_){return false}}
function user(){try{return auth&&auth.currentUser}catch(_){return null}}
function col(){var u=user();return u&&db?db.collection('users').doc(u.uid).collection('notifications'):null}
async function deleteIds(ids){var c=col();if(!c)throw new Error('Oturum yok');ids=Array.from(new Set((ids||[]).filter(Boolean)));for(var i=0;i<ids.length;i+=400){var b=db.batch();ids.slice(i,i+400).forEach(function(id){b.delete(c.doc(id))});await b.commit()}return ids.length}
async function clearAll(){var c=col();if(!c)throw new Error('Oturum yok');var n=0;for(var pass=0;pass<30;pass++){var s=await c.limit(400).get();if(s.empty)break;var b=db.batch();s.docs.forEach(function(x){b.delete(x.ref)});await b.commit();n+=s.size;if(s.size<400)break}return n}
function ensureClear(){var sh=d.getElementById('nava-app-notifications-v9');if(!sh)return null;var a=sh.querySelector('.nava-app-notification-head-actions-v9');if(!a)return null;var btn=d.getElementById('nava-notification-clear-all-v12161');if(btn){if(btn.parentNode!==a)a.insertBefore(btn,a.querySelector('.nava-app-sheet-close-v9')||null);return btn}btn=d.createElement('button');btn.type='button';btn.id='nava-notification-clear-all-v12161';btn.textContent='Tümünü temizle';btn.setAttribute('aria-label','Tüm bildirimleri temizle');btn.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();if(btn.disabled)return;btn.disabled=true;var old=btn.textContent;btn.textContent='Temizleniyor…';clearAll().then(function(n){btn.textContent=n?'Temizlendi':'Bildirim yok'}).catch(function(err){console.error('Nava bildirim temizleme:',err);btn.textContent='Tekrar dene'}).finally(function(){setTimeout(function(){btn.disabled=false;btn.textContent=old},1100)})});a.insertBefore(btn,a.querySelector('.nava-app-sheet-close-v9')||null);return btn}
function decorateRows(){var sh=d.getElementById('nava-app-notifications-v9');if(!sh)return;ensureClear();var rows=[].slice.call(sh.querySelectorAll('.nava-app-notification-row-v9'));rows.forEach(function(row,i){var item=docs[i];if(!item||!item.id)return;row.dataset.navaNotificationId=item.id;var x=row.querySelector('.nava-notification-delete-v12161');if(!x){x=d.createElement('span');x.className='nava-notification-delete-v12161';x.setAttribute('role','button');x.setAttribute('tabindex','0');x.setAttribute('aria-label','Bildirimi sil');x.setAttribute('title','Bildirimi sil');x.textContent='×';var del=function(e){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();var id=row.dataset.navaNotificationId;if(!id||x.dataset.busy==='1')return;x.dataset.busy='1';x.textContent='…';deleteIds([id]).catch(function(err){console.error('Nava bildirim silme:',err);x.dataset.busy='';x.textContent='×'})};x.addEventListener('click',del,true);x.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){del(e)}});row.append(x)}})}
function subscribe(u){if(unsub){try{unsub()}catch(_){}unsub=null}docs=[];lastUid=u&&u.uid||'';decorateRows();if(!u)return;try{unsub=db.collection('users').doc(u.uid).collection('notifications').orderBy('createdAt','desc').limit(40).onSnapshot(function(s){docs=s.docs.map(function(x){return{id:x.id,data:x.data()||{}}});setTimeout(decorateRows,0)},function(err){console.error('Nava 61 bildirim dinleyici:',err)})}catch(err){console.error('Nava 61 bildirim subscribe:',err)}}
function boot(){if(!ready()){setTimeout(boot,250);return}if(!authUnsub)authUnsub=auth.onAuthStateChanged(subscribe);ensureClear();decorateRows();if(!observer&&d.body){observer=new MutationObserver(function(){ensureClear();decorateRows();var u=user(),uid=u&&u.uid||'';if(uid!==lastUid)subscribe(u)});observer.observe(d.body,{childList:true,subtree:true})}}
if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
d.addEventListener('click',function(e){var t=e.target&&e.target.closest?e.target.closest('#nava-app-bell,[data-nava-notifications-open]'):null;if(t){setTimeout(function(){ensureClear();decorateRows()},0);setTimeout(function(){ensureClear();decorateRows()},180)}},true);
})(document,window);
